// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BodyCollision : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static BodyCollision GetRootAsBodyCollision(ByteBuffer _bb) { return GetRootAsBodyCollision(_bb, new BodyCollision()); }
  public static BodyCollision GetRootAsBodyCollision(ByteBuffer _bb, BodyCollision obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BodyCollision __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gfl.scene.fb.CollisionShapeData ShapeType { get { int o = __p.__offset(4); return o != 0 ? (gfl.scene.fb.CollisionShapeData)__p.bb.Get(o + __p.bb_pos) : gfl.scene.fb.CollisionShapeData.NONE; } }
  public TTable? Shape<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public gfl.scene.fb.SphereShape ShapeAsSphereShape() { return Shape<gfl.scene.fb.SphereShape>().Value; }
  public gfl.scene.fb.BoxShape ShapeAsBoxShape() { return Shape<gfl.scene.fb.BoxShape>().Value; }
  public gfl.scene.fb.CapsuleShape ShapeAsCapsuleShape() { return Shape<gfl.scene.fb.CapsuleShape>().Value; }
  public gfl.scene.fb.ModelShape ShapeAsModelShape() { return Shape<gfl.scene.fb.ModelShape>().Value; }
  public gfl.scene.fb.CompoundShape ShapeAsCompoundShape() { return Shape<gfl.scene.fb.CompoundShape>().Value; }
  public gfl.scene.fb.PencilShape ShapeAsPencilShape() { return Shape<gfl.scene.fb.PencilShape>().Value; }
  public gfl.scene.fb.MotionType MotionType { get { int o = __p.__offset(8); return o != 0 ? (gfl.scene.fb.MotionType)__p.bb.GetInt(o + __p.bb_pos) : gfl.scene.fb.MotionType.Static; } }
  public bool Trigger { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool TriggerModifiable { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool StartWithDisabled { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public int Layer { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool SyncParentScaleEnabled { get { int o = __p.__offset(18); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public gfl.scene.fb.CollisionMaterial? Material { get { int o = __p.__offset(20); return o != 0 ? (gfl.scene.fb.CollisionMaterial?)(new gfl.scene.fb.CollisionMaterial()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string CollisionName { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCollisionNameBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetCollisionNameBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetCollisionNameArray() { return __p.__vector_as_array<byte>(22); }
  public bool MaterialModifiable { get { int o = __p.__offset(24); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool NotChangeParameters { get { int o = __p.__offset(26); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool DisableEventTrigger { get { int o = __p.__offset(28); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<gfl.scene.fb.BodyCollision> CreateBodyCollision(FlatBufferBuilder builder,
      gfl.scene.fb.CollisionShapeData shape_type = gfl.scene.fb.CollisionShapeData.NONE,
      int shapeOffset = 0,
      gfl.scene.fb.MotionType motionType = gfl.scene.fb.MotionType.Static,
      bool trigger = false,
      bool triggerModifiable = false,
      bool startWithDisabled = false,
      int layer = 0,
      bool syncParentScaleEnabled = false,
      Offset<gfl.scene.fb.CollisionMaterial> materialOffset = default(Offset<gfl.scene.fb.CollisionMaterial>),
      StringOffset collisionNameOffset = default(StringOffset),
      bool materialModifiable = false,
      bool notChangeParameters = false,
      bool disableEventTrigger = false) {
    builder.StartTable(13);
    BodyCollision.AddCollisionName(builder, collisionNameOffset);
    BodyCollision.AddMaterial(builder, materialOffset);
    BodyCollision.AddLayer(builder, layer);
    BodyCollision.AddMotionType(builder, motionType);
    BodyCollision.AddShape(builder, shapeOffset);
    BodyCollision.AddDisableEventTrigger(builder, disableEventTrigger);
    BodyCollision.AddNotChangeParameters(builder, notChangeParameters);
    BodyCollision.AddMaterialModifiable(builder, materialModifiable);
    BodyCollision.AddSyncParentScaleEnabled(builder, syncParentScaleEnabled);
    BodyCollision.AddStartWithDisabled(builder, startWithDisabled);
    BodyCollision.AddTriggerModifiable(builder, triggerModifiable);
    BodyCollision.AddTrigger(builder, trigger);
    BodyCollision.AddShapeType(builder, shape_type);
    return BodyCollision.EndBodyCollision(builder);
  }

  public static void StartBodyCollision(FlatBufferBuilder builder) { builder.StartTable(13); }
  public static void AddShapeType(FlatBufferBuilder builder, gfl.scene.fb.CollisionShapeData shapeType) { builder.AddByte(0, (byte)shapeType, 0); }
  public static void AddShape(FlatBufferBuilder builder, int shapeOffset) { builder.AddOffset(1, shapeOffset, 0); }
  public static void AddMotionType(FlatBufferBuilder builder, gfl.scene.fb.MotionType motionType) { builder.AddInt(2, (int)motionType, 0); }
  public static void AddTrigger(FlatBufferBuilder builder, bool trigger) { builder.AddBool(3, trigger, false); }
  public static void AddTriggerModifiable(FlatBufferBuilder builder, bool triggerModifiable) { builder.AddBool(4, triggerModifiable, false); }
  public static void AddStartWithDisabled(FlatBufferBuilder builder, bool startWithDisabled) { builder.AddBool(5, startWithDisabled, false); }
  public static void AddLayer(FlatBufferBuilder builder, int layer) { builder.AddInt(6, layer, 0); }
  public static void AddSyncParentScaleEnabled(FlatBufferBuilder builder, bool syncParentScaleEnabled) { builder.AddBool(7, syncParentScaleEnabled, false); }
  public static void AddMaterial(FlatBufferBuilder builder, Offset<gfl.scene.fb.CollisionMaterial> materialOffset) { builder.AddOffset(8, materialOffset.Value, 0); }
  public static void AddCollisionName(FlatBufferBuilder builder, StringOffset collisionNameOffset) { builder.AddOffset(9, collisionNameOffset.Value, 0); }
  public static void AddMaterialModifiable(FlatBufferBuilder builder, bool materialModifiable) { builder.AddBool(10, materialModifiable, false); }
  public static void AddNotChangeParameters(FlatBufferBuilder builder, bool notChangeParameters) { builder.AddBool(11, notChangeParameters, false); }
  public static void AddDisableEventTrigger(FlatBufferBuilder builder, bool disableEventTrigger) { builder.AddBool(12, disableEventTrigger, false); }
  public static Offset<gfl.scene.fb.BodyCollision> EndBodyCollision(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.BodyCollision>(o);
  }
  public BodyCollisionT UnPack() {
    var _o = new BodyCollisionT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(BodyCollisionT _o) {
    _o.Shape = new gfl.scene.fb.CollisionShapeDataUnion();
    _o.Shape.Type = this.ShapeType;
    switch (this.ShapeType) {
      default: break;
      case gfl.scene.fb.CollisionShapeData.SphereShape:
        _o.Shape.Value = this.Shape<gfl.scene.fb.SphereShape>().HasValue ? this.Shape<gfl.scene.fb.SphereShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.BoxShape:
        _o.Shape.Value = this.Shape<gfl.scene.fb.BoxShape>().HasValue ? this.Shape<gfl.scene.fb.BoxShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.CapsuleShape:
        _o.Shape.Value = this.Shape<gfl.scene.fb.CapsuleShape>().HasValue ? this.Shape<gfl.scene.fb.CapsuleShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.ModelShape:
        _o.Shape.Value = this.Shape<gfl.scene.fb.ModelShape>().HasValue ? this.Shape<gfl.scene.fb.ModelShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.CompoundShape:
        _o.Shape.Value = this.Shape<gfl.scene.fb.CompoundShape>().HasValue ? this.Shape<gfl.scene.fb.CompoundShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.PencilShape:
        _o.Shape.Value = this.Shape<gfl.scene.fb.PencilShape>().HasValue ? this.Shape<gfl.scene.fb.PencilShape>().Value.UnPack() : null;
        break;
    }
    _o.MotionType = this.MotionType;
    _o.Trigger = this.Trigger;
    _o.TriggerModifiable = this.TriggerModifiable;
    _o.StartWithDisabled = this.StartWithDisabled;
    _o.Layer = this.Layer;
    _o.SyncParentScaleEnabled = this.SyncParentScaleEnabled;
    _o.Material = this.Material.HasValue ? this.Material.Value.UnPack() : null;
    _o.CollisionName = this.CollisionName;
    _o.MaterialModifiable = this.MaterialModifiable;
    _o.NotChangeParameters = this.NotChangeParameters;
    _o.DisableEventTrigger = this.DisableEventTrigger;
  }
  public static Offset<gfl.scene.fb.BodyCollision> Pack(FlatBufferBuilder builder, BodyCollisionT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.BodyCollision>);
    var _shape_type = _o.Shape == null ? gfl.scene.fb.CollisionShapeData.NONE : _o.Shape.Type;
    var _shape = _o.Shape == null ? 0 : gfl.scene.fb.CollisionShapeDataUnion.Pack(builder, _o.Shape);
    var _material = _o.Material == null ? default(Offset<gfl.scene.fb.CollisionMaterial>) : gfl.scene.fb.CollisionMaterial.Pack(builder, _o.Material);
    var _collisionName = _o.CollisionName == null ? default(StringOffset) : builder.CreateString(_o.CollisionName);
    return CreateBodyCollision(
      builder,
      _shape_type,
      _shape,
      _o.MotionType,
      _o.Trigger,
      _o.TriggerModifiable,
      _o.StartWithDisabled,
      _o.Layer,
      _o.SyncParentScaleEnabled,
      _material,
      _collisionName,
      _o.MaterialModifiable,
      _o.NotChangeParameters,
      _o.DisableEventTrigger);
  }
}

public class BodyCollisionT
{
  public gfl.scene.fb.CollisionShapeDataUnion Shape { get; set; }
  public gfl.scene.fb.MotionType MotionType { get; set; }
  public bool Trigger { get; set; }
  public bool TriggerModifiable { get; set; }
  public bool StartWithDisabled { get; set; }
  public int Layer { get; set; }
  public bool SyncParentScaleEnabled { get; set; }
  public gfl.scene.fb.CollisionMaterialT Material { get; set; }
  public string CollisionName { get; set; }
  public bool MaterialModifiable { get; set; }
  public bool NotChangeParameters { get; set; }
  public bool DisableEventTrigger { get; set; }

  public BodyCollisionT() {
    this.Shape = null;
    this.MotionType = gfl.scene.fb.MotionType.Static;
    this.Trigger = false;
    this.TriggerModifiable = false;
    this.StartWithDisabled = false;
    this.Layer = 0;
    this.SyncParentScaleEnabled = false;
    this.Material = null;
    this.CollisionName = null;
    this.MaterialModifiable = false;
    this.NotChangeParameters = false;
    this.DisableEventTrigger = false;
  }
}


}
