// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterCreationUnit : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static CharacterCreationUnit GetRootAsCharacterCreationUnit(ByteBuffer _bb) { return GetRootAsCharacterCreationUnit(_bb, new CharacterCreationUnit()); }
  public static CharacterCreationUnit GetRootAsCharacterCreationUnit(ByteBuffer _bb, CharacterCreationUnit obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterCreationUnit __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Category { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCategoryBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetCategoryBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetCategoryArray() { return __p.__vector_as_array<byte>(4); }
  public string FilePath { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilePathBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetFilePathBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetFilePathArray() { return __p.__vector_as_array<byte>(6); }
  public string Label { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLabelBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetLabelBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetLabelArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<gfl.scene.fb.CharacterCreationUnit> CreateCharacterCreationUnit(FlatBufferBuilder builder,
      StringOffset categoryOffset = default(StringOffset),
      StringOffset filePathOffset = default(StringOffset),
      StringOffset labelOffset = default(StringOffset)) {
    builder.StartTable(3);
    CharacterCreationUnit.AddLabel(builder, labelOffset);
    CharacterCreationUnit.AddFilePath(builder, filePathOffset);
    CharacterCreationUnit.AddCategory(builder, categoryOffset);
    return CharacterCreationUnit.EndCharacterCreationUnit(builder);
  }

  public static void StartCharacterCreationUnit(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddCategory(FlatBufferBuilder builder, StringOffset categoryOffset) { builder.AddOffset(0, categoryOffset.Value, 0); }
  public static void AddFilePath(FlatBufferBuilder builder, StringOffset filePathOffset) { builder.AddOffset(1, filePathOffset.Value, 0); }
  public static void AddLabel(FlatBufferBuilder builder, StringOffset labelOffset) { builder.AddOffset(2, labelOffset.Value, 0); }
  public static Offset<gfl.scene.fb.CharacterCreationUnit> EndCharacterCreationUnit(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.CharacterCreationUnit>(o);
  }
  public CharacterCreationUnitT UnPack() {
    var _o = new CharacterCreationUnitT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CharacterCreationUnitT _o) {
    _o.Category = this.Category;
    _o.FilePath = this.FilePath;
    _o.Label = this.Label;
  }
  public static Offset<gfl.scene.fb.CharacterCreationUnit> Pack(FlatBufferBuilder builder, CharacterCreationUnitT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.CharacterCreationUnit>);
    var _category = _o.Category == null ? default(StringOffset) : builder.CreateString(_o.Category);
    var _filePath = _o.FilePath == null ? default(StringOffset) : builder.CreateString(_o.FilePath);
    var _label = _o.Label == null ? default(StringOffset) : builder.CreateString(_o.Label);
    return CreateCharacterCreationUnit(
      builder,
      _category,
      _filePath,
      _label);
  }
}

public class CharacterCreationUnitT
{
  public string Category { get; set; }
  public string FilePath { get; set; }
  public string Label { get; set; }

  public CharacterCreationUnitT() {
    this.Category = null;
    this.FilePath = null;
    this.Label = null;
  }
}


}
