// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterCreationMasterComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static CharacterCreationMasterComponent GetRootAsCharacterCreationMasterComponent(ByteBuffer _bb) { return GetRootAsCharacterCreationMasterComponent(_bb, new CharacterCreationMasterComponent()); }
  public static CharacterCreationMasterComponent GetRootAsCharacterCreationMasterComponent(ByteBuffer _bb, CharacterCreationMasterComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterCreationMasterComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ResourceName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetResourceNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetResourceNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetResourceNameArray() { return __p.__vector_as_array<byte>(4); }
  public bool OverrideLodDistance { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float LodDistance0 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float LodDistance1 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float LodDistance2 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public bool JointPriorityEnabled { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float JointPriorityDistance0 { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int JointMaxPriority0 { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float JointPriorityDistance1 { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int JointMaxPriority1 { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float JointPriorityDistance2 { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int JointMaxPriority2 { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float JointPriorityDistance3 { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int JointMaxPriority3 { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int AnimationSlot { get { int o = __p.__offset(32); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public gfl.scene.fb.CharacterCreationUnit? CcdatamList(int j) { int o = __p.__offset(34); return o != 0 ? (gfl.scene.fb.CharacterCreationUnit?)(new gfl.scene.fb.CharacterCreationUnit()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CcdatamListLength { get { int o = __p.__offset(34); return o != 0 ? __p.__vector_len(o) : 0; } }
  public gfl.scene.fb.SysVis? SysvisList(int j) { int o = __p.__offset(36); return o != 0 ? (gfl.scene.fb.SysVis?)(new gfl.scene.fb.SysVis()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SysvisListLength { get { int o = __p.__offset(36); return o != 0 ? __p.__vector_len(o) : 0; } }
  public bool VisibleOnInit { get { int o = __p.__offset(38); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }

  public static Offset<gfl.scene.fb.CharacterCreationMasterComponent> CreateCharacterCreationMasterComponent(FlatBufferBuilder builder,
      StringOffset resourceNameOffset = default(StringOffset),
      bool overrideLodDistance = false,
      float lodDistance0 = 0.0f,
      float lodDistance1 = 0.0f,
      float lodDistance2 = 0.0f,
      bool jointPriorityEnabled = false,
      float jointPriorityDistance0 = 0.0f,
      int jointMaxPriority0 = 0,
      float jointPriorityDistance1 = 0.0f,
      int jointMaxPriority1 = 0,
      float jointPriorityDistance2 = 0.0f,
      int jointMaxPriority2 = 0,
      float jointPriorityDistance3 = 0.0f,
      int jointMaxPriority3 = 0,
      int animationSlot = 0,
      VectorOffset ccdatamListOffset = default(VectorOffset),
      VectorOffset sysvisListOffset = default(VectorOffset),
      bool visibleOnInit = true) {
    builder.StartTable(18);
    CharacterCreationMasterComponent.AddSysvisList(builder, sysvisListOffset);
    CharacterCreationMasterComponent.AddCcdatamList(builder, ccdatamListOffset);
    CharacterCreationMasterComponent.AddAnimationSlot(builder, animationSlot);
    CharacterCreationMasterComponent.AddJointMaxPriority3(builder, jointMaxPriority3);
    CharacterCreationMasterComponent.AddJointPriorityDistance3(builder, jointPriorityDistance3);
    CharacterCreationMasterComponent.AddJointMaxPriority2(builder, jointMaxPriority2);
    CharacterCreationMasterComponent.AddJointPriorityDistance2(builder, jointPriorityDistance2);
    CharacterCreationMasterComponent.AddJointMaxPriority1(builder, jointMaxPriority1);
    CharacterCreationMasterComponent.AddJointPriorityDistance1(builder, jointPriorityDistance1);
    CharacterCreationMasterComponent.AddJointMaxPriority0(builder, jointMaxPriority0);
    CharacterCreationMasterComponent.AddJointPriorityDistance0(builder, jointPriorityDistance0);
    CharacterCreationMasterComponent.AddLodDistance2(builder, lodDistance2);
    CharacterCreationMasterComponent.AddLodDistance1(builder, lodDistance1);
    CharacterCreationMasterComponent.AddLodDistance0(builder, lodDistance0);
    CharacterCreationMasterComponent.AddResourceName(builder, resourceNameOffset);
    CharacterCreationMasterComponent.AddVisibleOnInit(builder, visibleOnInit);
    CharacterCreationMasterComponent.AddJointPriorityEnabled(builder, jointPriorityEnabled);
    CharacterCreationMasterComponent.AddOverrideLodDistance(builder, overrideLodDistance);
    return CharacterCreationMasterComponent.EndCharacterCreationMasterComponent(builder);
  }

  public static void StartCharacterCreationMasterComponent(FlatBufferBuilder builder) { builder.StartTable(18); }
  public static void AddResourceName(FlatBufferBuilder builder, StringOffset resourceNameOffset) { builder.AddOffset(0, resourceNameOffset.Value, 0); }
  public static void AddOverrideLodDistance(FlatBufferBuilder builder, bool overrideLodDistance) { builder.AddBool(1, overrideLodDistance, false); }
  public static void AddLodDistance0(FlatBufferBuilder builder, float lodDistance0) { builder.AddFloat(2, lodDistance0, 0.0f); }
  public static void AddLodDistance1(FlatBufferBuilder builder, float lodDistance1) { builder.AddFloat(3, lodDistance1, 0.0f); }
  public static void AddLodDistance2(FlatBufferBuilder builder, float lodDistance2) { builder.AddFloat(4, lodDistance2, 0.0f); }
  public static void AddJointPriorityEnabled(FlatBufferBuilder builder, bool jointPriorityEnabled) { builder.AddBool(5, jointPriorityEnabled, false); }
  public static void AddJointPriorityDistance0(FlatBufferBuilder builder, float jointPriorityDistance0) { builder.AddFloat(6, jointPriorityDistance0, 0.0f); }
  public static void AddJointMaxPriority0(FlatBufferBuilder builder, int jointMaxPriority0) { builder.AddInt(7, jointMaxPriority0, 0); }
  public static void AddJointPriorityDistance1(FlatBufferBuilder builder, float jointPriorityDistance1) { builder.AddFloat(8, jointPriorityDistance1, 0.0f); }
  public static void AddJointMaxPriority1(FlatBufferBuilder builder, int jointMaxPriority1) { builder.AddInt(9, jointMaxPriority1, 0); }
  public static void AddJointPriorityDistance2(FlatBufferBuilder builder, float jointPriorityDistance2) { builder.AddFloat(10, jointPriorityDistance2, 0.0f); }
  public static void AddJointMaxPriority2(FlatBufferBuilder builder, int jointMaxPriority2) { builder.AddInt(11, jointMaxPriority2, 0); }
  public static void AddJointPriorityDistance3(FlatBufferBuilder builder, float jointPriorityDistance3) { builder.AddFloat(12, jointPriorityDistance3, 0.0f); }
  public static void AddJointMaxPriority3(FlatBufferBuilder builder, int jointMaxPriority3) { builder.AddInt(13, jointMaxPriority3, 0); }
  public static void AddAnimationSlot(FlatBufferBuilder builder, int animationSlot) { builder.AddInt(14, animationSlot, 0); }
  public static void AddCcdatamList(FlatBufferBuilder builder, VectorOffset ccdatamListOffset) { builder.AddOffset(15, ccdatamListOffset.Value, 0); }
  public static VectorOffset CreateCcdatamListVector(FlatBufferBuilder builder, Offset<gfl.scene.fb.CharacterCreationUnit>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCcdatamListVectorBlock(FlatBufferBuilder builder, Offset<gfl.scene.fb.CharacterCreationUnit>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCcdatamListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<gfl.scene.fb.CharacterCreationUnit>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCcdatamListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<gfl.scene.fb.CharacterCreationUnit>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCcdatamListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSysvisList(FlatBufferBuilder builder, VectorOffset sysvisListOffset) { builder.AddOffset(16, sysvisListOffset.Value, 0); }
  public static VectorOffset CreateSysvisListVector(FlatBufferBuilder builder, Offset<gfl.scene.fb.SysVis>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSysvisListVectorBlock(FlatBufferBuilder builder, Offset<gfl.scene.fb.SysVis>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSysvisListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<gfl.scene.fb.SysVis>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSysvisListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<gfl.scene.fb.SysVis>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSysvisListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddVisibleOnInit(FlatBufferBuilder builder, bool visibleOnInit) { builder.AddBool(17, visibleOnInit, true); }
  public static Offset<gfl.scene.fb.CharacterCreationMasterComponent> EndCharacterCreationMasterComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.CharacterCreationMasterComponent>(o);
  }
  public static void FinishCharacterCreationMasterComponentBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.CharacterCreationMasterComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedCharacterCreationMasterComponentBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.CharacterCreationMasterComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public CharacterCreationMasterComponentT UnPack() {
    var _o = new CharacterCreationMasterComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CharacterCreationMasterComponentT _o) {
    _o.ResourceName = this.ResourceName;
    _o.OverrideLodDistance = this.OverrideLodDistance;
    _o.LodDistance0 = this.LodDistance0;
    _o.LodDistance1 = this.LodDistance1;
    _o.LodDistance2 = this.LodDistance2;
    _o.JointPriorityEnabled = this.JointPriorityEnabled;
    _o.JointPriorityDistance0 = this.JointPriorityDistance0;
    _o.JointMaxPriority0 = this.JointMaxPriority0;
    _o.JointPriorityDistance1 = this.JointPriorityDistance1;
    _o.JointMaxPriority1 = this.JointMaxPriority1;
    _o.JointPriorityDistance2 = this.JointPriorityDistance2;
    _o.JointMaxPriority2 = this.JointMaxPriority2;
    _o.JointPriorityDistance3 = this.JointPriorityDistance3;
    _o.JointMaxPriority3 = this.JointMaxPriority3;
    _o.AnimationSlot = this.AnimationSlot;
    _o.CcdatamList = new List<gfl.scene.fb.CharacterCreationUnitT>();
    for (var _j = 0; _j < this.CcdatamListLength; ++_j) {_o.CcdatamList.Add(this.CcdatamList(_j).HasValue ? this.CcdatamList(_j).Value.UnPack() : null);}
    _o.SysvisList = new List<gfl.scene.fb.SysVisT>();
    for (var _j = 0; _j < this.SysvisListLength; ++_j) {_o.SysvisList.Add(this.SysvisList(_j).HasValue ? this.SysvisList(_j).Value.UnPack() : null);}
    _o.VisibleOnInit = this.VisibleOnInit;
  }
  public static Offset<gfl.scene.fb.CharacterCreationMasterComponent> Pack(FlatBufferBuilder builder, CharacterCreationMasterComponentT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.CharacterCreationMasterComponent>);
    var _resourceName = _o.ResourceName == null ? default(StringOffset) : builder.CreateString(_o.ResourceName);
    var _ccdatamList = default(VectorOffset);
    if (_o.CcdatamList != null) {
      var __ccdatamList = new Offset<gfl.scene.fb.CharacterCreationUnit>[_o.CcdatamList.Count];
      for (var _j = 0; _j < __ccdatamList.Length; ++_j) { __ccdatamList[_j] = gfl.scene.fb.CharacterCreationUnit.Pack(builder, _o.CcdatamList[_j]); }
      _ccdatamList = CreateCcdatamListVector(builder, __ccdatamList);
    }
    var _sysvisList = default(VectorOffset);
    if (_o.SysvisList != null) {
      var __sysvisList = new Offset<gfl.scene.fb.SysVis>[_o.SysvisList.Count];
      for (var _j = 0; _j < __sysvisList.Length; ++_j) { __sysvisList[_j] = gfl.scene.fb.SysVis.Pack(builder, _o.SysvisList[_j]); }
      _sysvisList = CreateSysvisListVector(builder, __sysvisList);
    }
    return CreateCharacterCreationMasterComponent(
      builder,
      _resourceName,
      _o.OverrideLodDistance,
      _o.LodDistance0,
      _o.LodDistance1,
      _o.LodDistance2,
      _o.JointPriorityEnabled,
      _o.JointPriorityDistance0,
      _o.JointMaxPriority0,
      _o.JointPriorityDistance1,
      _o.JointMaxPriority1,
      _o.JointPriorityDistance2,
      _o.JointMaxPriority2,
      _o.JointPriorityDistance3,
      _o.JointMaxPriority3,
      _o.AnimationSlot,
      _ccdatamList,
      _sysvisList,
      _o.VisibleOnInit);
  }
}

public class CharacterCreationMasterComponentT
{
  public string ResourceName { get; set; }
  public bool OverrideLodDistance { get; set; }
  public float LodDistance0 { get; set; }
  public float LodDistance1 { get; set; }
  public float LodDistance2 { get; set; }
  public bool JointPriorityEnabled { get; set; }
  public float JointPriorityDistance0 { get; set; }
  public int JointMaxPriority0 { get; set; }
  public float JointPriorityDistance1 { get; set; }
  public int JointMaxPriority1 { get; set; }
  public float JointPriorityDistance2 { get; set; }
  public int JointMaxPriority2 { get; set; }
  public float JointPriorityDistance3 { get; set; }
  public int JointMaxPriority3 { get; set; }
  public int AnimationSlot { get; set; }
  public List<gfl.scene.fb.CharacterCreationUnitT> CcdatamList { get; set; }
  public List<gfl.scene.fb.SysVisT> SysvisList { get; set; }
  public bool VisibleOnInit { get; set; }

  public CharacterCreationMasterComponentT() {
    this.ResourceName = null;
    this.OverrideLodDistance = false;
    this.LodDistance0 = 0.0f;
    this.LodDistance1 = 0.0f;
    this.LodDistance2 = 0.0f;
    this.JointPriorityEnabled = false;
    this.JointPriorityDistance0 = 0.0f;
    this.JointMaxPriority0 = 0;
    this.JointPriorityDistance1 = 0.0f;
    this.JointMaxPriority1 = 0;
    this.JointPriorityDistance2 = 0.0f;
    this.JointMaxPriority2 = 0;
    this.JointPriorityDistance3 = 0.0f;
    this.JointMaxPriority3 = 0;
    this.AnimationSlot = 0;
    this.CcdatamList = null;
    this.SysvisList = null;
    this.VisibleOnInit = true;
  }
  public static CharacterCreationMasterComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return CharacterCreationMasterComponent.GetRootAsCharacterCreationMasterComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    CharacterCreationMasterComponent.FinishCharacterCreationMasterComponentBuffer(fbb, CharacterCreationMasterComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
