// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CollisionShape : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static CollisionShape GetRootAsCollisionShape(ByteBuffer _bb) { return GetRootAsCollisionShape(_bb, new CollisionShape()); }
  public static CollisionShape GetRootAsCollisionShape(ByteBuffer _bb, CollisionShape obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CollisionShape __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gfl.scene.fb.CollisionShapeData DataType { get { int o = __p.__offset(4); return o != 0 ? (gfl.scene.fb.CollisionShapeData)__p.bb.Get(o + __p.bb_pos) : gfl.scene.fb.CollisionShapeData.NONE; } }
  public TTable? Data<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public gfl.scene.fb.SphereShape DataAsSphereShape() { return Data<gfl.scene.fb.SphereShape>().Value; }
  public gfl.scene.fb.BoxShape DataAsBoxShape() { return Data<gfl.scene.fb.BoxShape>().Value; }
  public gfl.scene.fb.CapsuleShape DataAsCapsuleShape() { return Data<gfl.scene.fb.CapsuleShape>().Value; }
  public gfl.scene.fb.ModelShape DataAsModelShape() { return Data<gfl.scene.fb.ModelShape>().Value; }
  public gfl.scene.fb.CompoundShape DataAsCompoundShape() { return Data<gfl.scene.fb.CompoundShape>().Value; }
  public gfl.scene.fb.PencilShape DataAsPencilShape() { return Data<gfl.scene.fb.PencilShape>().Value; }

  public static Offset<gfl.scene.fb.CollisionShape> CreateCollisionShape(FlatBufferBuilder builder,
      gfl.scene.fb.CollisionShapeData data_type = gfl.scene.fb.CollisionShapeData.NONE,
      int dataOffset = 0) {
    builder.StartTable(2);
    CollisionShape.AddData(builder, dataOffset);
    CollisionShape.AddDataType(builder, data_type);
    return CollisionShape.EndCollisionShape(builder);
  }

  public static void StartCollisionShape(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDataType(FlatBufferBuilder builder, gfl.scene.fb.CollisionShapeData dataType) { builder.AddByte(0, (byte)dataType, 0); }
  public static void AddData(FlatBufferBuilder builder, int dataOffset) { builder.AddOffset(1, dataOffset, 0); }
  public static Offset<gfl.scene.fb.CollisionShape> EndCollisionShape(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.CollisionShape>(o);
  }
  public static void FinishCollisionShapeBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.CollisionShape> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedCollisionShapeBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.CollisionShape> offset) { builder.FinishSizePrefixed(offset.Value); }
  public CollisionShapeT UnPack() {
    var _o = new CollisionShapeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CollisionShapeT _o) {
    _o.Data = new gfl.scene.fb.CollisionShapeDataUnion();
    _o.Data.Type = this.DataType;
    switch (this.DataType) {
      default: break;
      case gfl.scene.fb.CollisionShapeData.SphereShape:
        _o.Data.Value = this.Data<gfl.scene.fb.SphereShape>().HasValue ? this.Data<gfl.scene.fb.SphereShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.BoxShape:
        _o.Data.Value = this.Data<gfl.scene.fb.BoxShape>().HasValue ? this.Data<gfl.scene.fb.BoxShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.CapsuleShape:
        _o.Data.Value = this.Data<gfl.scene.fb.CapsuleShape>().HasValue ? this.Data<gfl.scene.fb.CapsuleShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.ModelShape:
        _o.Data.Value = this.Data<gfl.scene.fb.ModelShape>().HasValue ? this.Data<gfl.scene.fb.ModelShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.CompoundShape:
        _o.Data.Value = this.Data<gfl.scene.fb.CompoundShape>().HasValue ? this.Data<gfl.scene.fb.CompoundShape>().Value.UnPack() : null;
        break;
      case gfl.scene.fb.CollisionShapeData.PencilShape:
        _o.Data.Value = this.Data<gfl.scene.fb.PencilShape>().HasValue ? this.Data<gfl.scene.fb.PencilShape>().Value.UnPack() : null;
        break;
    }
  }
  public static Offset<gfl.scene.fb.CollisionShape> Pack(FlatBufferBuilder builder, CollisionShapeT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.CollisionShape>);
    var _data_type = _o.Data == null ? gfl.scene.fb.CollisionShapeData.NONE : _o.Data.Type;
    var _data = _o.Data == null ? 0 : gfl.scene.fb.CollisionShapeDataUnion.Pack(builder, _o.Data);
    return CreateCollisionShape(
      builder,
      _data_type,
      _data);
  }
}

public class CollisionShapeT
{
  public gfl.scene.fb.CollisionShapeDataUnion Data { get; set; }

  public CollisionShapeT() {
    this.Data = null;
  }
  public static CollisionShapeT DeserializeFromBinary(byte[] fbBuffer) {
    return CollisionShape.GetRootAsCollisionShape(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    CollisionShape.FinishCollisionShapeBuffer(fbb, CollisionShape.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
