// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

public enum CollisionData : byte
{
  NONE = 0,
  BodyCollision = 1,
  CharacterCollision = 2,
};

public class CollisionDataUnion {
  public CollisionData Type { get; set; }
  public object Value { get; set; }

  public CollisionDataUnion() {
    this.Type = CollisionData.NONE;
    this.Value = null;
  }

  public T As<T>() where T : class { return this.Value as T; }
  public gfl.scene.fb.BodyCollisionT AsBodyCollision() { return this.As<gfl.scene.fb.BodyCollisionT>(); }
  public static CollisionDataUnion FromBodyCollision(gfl.scene.fb.BodyCollisionT _bodycollision) { return new CollisionDataUnion{ Type = CollisionData.BodyCollision, Value = _bodycollision }; }
  public gfl.scene.fb.CharacterCollisionT AsCharacterCollision() { return this.As<gfl.scene.fb.CharacterCollisionT>(); }
  public static CollisionDataUnion FromCharacterCollision(gfl.scene.fb.CharacterCollisionT _charactercollision) { return new CollisionDataUnion{ Type = CollisionData.CharacterCollision, Value = _charactercollision }; }

  public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, CollisionDataUnion _o) {
    switch (_o.Type) {
      default: return 0;
      case CollisionData.BodyCollision: return gfl.scene.fb.BodyCollision.Pack(builder, _o.AsBodyCollision()).Value;
      case CollisionData.CharacterCollision: return gfl.scene.fb.CharacterCollision.Pack(builder, _o.AsCharacterCollision()).Value;
    }
  }
}


}
