// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CollisionMaterial : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static CollisionMaterial GetRootAsCollisionMaterial(ByteBuffer _bb) { return GetRootAsCollisionMaterial(_bb, new CollisionMaterial()); }
  public static CollisionMaterial GetRootAsCollisionMaterial(ByteBuffer _bb, CollisionMaterial obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CollisionMaterial __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Mass { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float DynamicFriction { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float StaticFriction { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Restitution { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<gfl.scene.fb.CollisionMaterial> CreateCollisionMaterial(FlatBufferBuilder builder,
      float mass = 0.0f,
      float dynamicFriction = 0.0f,
      float staticFriction = 0.0f,
      float restitution = 0.0f) {
    builder.StartTable(4);
    CollisionMaterial.AddRestitution(builder, restitution);
    CollisionMaterial.AddStaticFriction(builder, staticFriction);
    CollisionMaterial.AddDynamicFriction(builder, dynamicFriction);
    CollisionMaterial.AddMass(builder, mass);
    return CollisionMaterial.EndCollisionMaterial(builder);
  }

  public static void StartCollisionMaterial(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddMass(FlatBufferBuilder builder, float mass) { builder.AddFloat(0, mass, 0.0f); }
  public static void AddDynamicFriction(FlatBufferBuilder builder, float dynamicFriction) { builder.AddFloat(1, dynamicFriction, 0.0f); }
  public static void AddStaticFriction(FlatBufferBuilder builder, float staticFriction) { builder.AddFloat(2, staticFriction, 0.0f); }
  public static void AddRestitution(FlatBufferBuilder builder, float restitution) { builder.AddFloat(3, restitution, 0.0f); }
  public static Offset<gfl.scene.fb.CollisionMaterial> EndCollisionMaterial(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.CollisionMaterial>(o);
  }
  public CollisionMaterialT UnPack() {
    var _o = new CollisionMaterialT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CollisionMaterialT _o) {
    _o.Mass = this.Mass;
    _o.DynamicFriction = this.DynamicFriction;
    _o.StaticFriction = this.StaticFriction;
    _o.Restitution = this.Restitution;
  }
  public static Offset<gfl.scene.fb.CollisionMaterial> Pack(FlatBufferBuilder builder, CollisionMaterialT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.CollisionMaterial>);
    return CreateCollisionMaterial(
      builder,
      _o.Mass,
      _o.DynamicFriction,
      _o.StaticFriction,
      _o.Restitution);
  }
}

public class CollisionMaterialT
{
  public float Mass { get; set; }
  public float DynamicFriction { get; set; }
  public float StaticFriction { get; set; }
  public float Restitution { get; set; }

  public CollisionMaterialT() {
    this.Mass = 0.0f;
    this.DynamicFriction = 0.0f;
    this.StaticFriction = 0.0f;
    this.Restitution = 0.0f;
  }
}


}
