// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CombineLODConfigure : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static CombineLODConfigure GetRootAsCombineLODConfigure(ByteBuffer _bb) { return GetRootAsCombineLODConfigure(_bb, new CombineLODConfigure()); }
  public static CombineLODConfigure GetRootAsCombineLODConfigure(ByteBuffer _bb, CombineLODConfigure obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CombineLODConfigure __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ModelFilePath { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetModelFilePathBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetModelFilePathBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetModelFilePathArray() { return __p.__vector_as_array<byte>(4); }
  public string AnimationFilePath { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAnimationFilePathBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetAnimationFilePathBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetAnimationFilePathArray() { return __p.__vector_as_array<byte>(6); }
  public string ScriptPackageName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetScriptPackageNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetScriptPackageNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetScriptPackageNameArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<gfl.scene.fb.CombineLODConfigure> CreateCombineLODConfigure(FlatBufferBuilder builder,
      StringOffset modelFilePathOffset = default(StringOffset),
      StringOffset animationFilePathOffset = default(StringOffset),
      StringOffset scriptPackageNameOffset = default(StringOffset)) {
    builder.StartTable(3);
    CombineLODConfigure.AddScriptPackageName(builder, scriptPackageNameOffset);
    CombineLODConfigure.AddAnimationFilePath(builder, animationFilePathOffset);
    CombineLODConfigure.AddModelFilePath(builder, modelFilePathOffset);
    return CombineLODConfigure.EndCombineLODConfigure(builder);
  }

  public static void StartCombineLODConfigure(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddModelFilePath(FlatBufferBuilder builder, StringOffset modelFilePathOffset) { builder.AddOffset(0, modelFilePathOffset.Value, 0); }
  public static void AddAnimationFilePath(FlatBufferBuilder builder, StringOffset animationFilePathOffset) { builder.AddOffset(1, animationFilePathOffset.Value, 0); }
  public static void AddScriptPackageName(FlatBufferBuilder builder, StringOffset scriptPackageNameOffset) { builder.AddOffset(2, scriptPackageNameOffset.Value, 0); }
  public static Offset<gfl.scene.fb.CombineLODConfigure> EndCombineLODConfigure(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.CombineLODConfigure>(o);
  }
  public CombineLODConfigureT UnPack() {
    var _o = new CombineLODConfigureT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CombineLODConfigureT _o) {
    _o.ModelFilePath = this.ModelFilePath;
    _o.AnimationFilePath = this.AnimationFilePath;
    _o.ScriptPackageName = this.ScriptPackageName;
  }
  public static Offset<gfl.scene.fb.CombineLODConfigure> Pack(FlatBufferBuilder builder, CombineLODConfigureT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.CombineLODConfigure>);
    var _modelFilePath = _o.ModelFilePath == null ? default(StringOffset) : builder.CreateString(_o.ModelFilePath);
    var _animationFilePath = _o.AnimationFilePath == null ? default(StringOffset) : builder.CreateString(_o.AnimationFilePath);
    var _scriptPackageName = _o.ScriptPackageName == null ? default(StringOffset) : builder.CreateString(_o.ScriptPackageName);
    return CreateCombineLODConfigure(
      builder,
      _modelFilePath,
      _animationFilePath,
      _scriptPackageName);
  }
}

public class CombineLODConfigureT
{
  public string ModelFilePath { get; set; }
  public string AnimationFilePath { get; set; }
  public string ScriptPackageName { get; set; }

  public CombineLODConfigureT() {
    this.ModelFilePath = null;
    this.AnimationFilePath = null;
    this.ScriptPackageName = null;
  }
}


}
