// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

public enum DivisionType : sbyte
{
  Div1 = 0,
  Div2 = 1,
  Div4 = 2,
  Div8 = 3,
  Div16 = 4,
  Div32 = 5,
  Div64 = 6,
  Div128 = 7,
  Div256 = 8,
  Div512 = 9,
  Div1024 = 10,
};


}
