// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

public enum GridType : sbyte
{
  Octree = 0,
  Quadtree = 1,
  Hybridtree = 2,
};


}
