// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

public enum InputEventType : int
{
  Button = 0,
  Stick = 1,
};


}
