// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JointLod : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static JointLod GetRootAsJointLod(ByteBuffer _bb) { return GetRootAsJointLod(_bb, new JointLod()); }
  public static JointLod GetRootAsJointLod(ByteBuffer _bb, JointLod obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JointLod __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Distance { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int Priority { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<gfl.scene.fb.JointLod> CreateJointLod(FlatBufferBuilder builder,
      float distance = 0.0f,
      int priority = 0) {
    builder.StartTable(2);
    JointLod.AddPriority(builder, priority);
    JointLod.AddDistance(builder, distance);
    return JointLod.EndJointLod(builder);
  }

  public static void StartJointLod(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDistance(FlatBufferBuilder builder, float distance) { builder.AddFloat(0, distance, 0.0f); }
  public static void AddPriority(FlatBufferBuilder builder, int priority) { builder.AddInt(1, priority, 0); }
  public static Offset<gfl.scene.fb.JointLod> EndJointLod(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.JointLod>(o);
  }
  public JointLodT UnPack() {
    var _o = new JointLodT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(JointLodT _o) {
    _o.Distance = this.Distance;
    _o.Priority = this.Priority;
  }
  public static Offset<gfl.scene.fb.JointLod> Pack(FlatBufferBuilder builder, JointLodT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.JointLod>);
    return CreateJointLod(
      builder,
      _o.Distance,
      _o.Priority);
  }
}

public class JointLodT
{
  public float Distance { get; set; }
  public int Priority { get; set; }

  public JointLodT() {
    this.Distance = 0.0f;
    this.Priority = 0;
  }
}


}
