// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ModelComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ModelComponent GetRootAsModelComponent(ByteBuffer _bb) { return GetRootAsModelComponent(_bb, new ModelComponent()); }
  public static ModelComponent GetRootAsModelComponent(ByteBuffer _bb, ModelComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ModelComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string FilePath { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilePathBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFilePathBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFilePathArray() { return __p.__vector_as_array<byte>(4); }
  public string ResourceName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetResourceNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetResourceNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetResourceNameArray() { return __p.__vector_as_array<byte>(6); }
  public string MetaFilePath { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMetaFilePathBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetMetaFilePathBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetMetaFilePathArray() { return __p.__vector_as_array<byte>(8); }
  public string MetaItemName { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMetaItemNameBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetMetaItemNameBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetMetaItemNameArray() { return __p.__vector_as_array<byte>(10); }
  public bool OverrideLodDistance { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float LodDistance0 { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float LodDistance1 { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float LodDistance2 { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public bool JointPriorityEnabled { get { int o = __p.__offset(20); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float JointPriorityDistance0 { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int JointMaxPriority0 { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float JointPriorityDistance1 { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int JointMaxPriority1 { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float JointPriorityDistance2 { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int JointMaxPriority2 { get { int o = __p.__offset(32); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float JointPriorityDistance3 { get { int o = __p.__offset(34); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int JointMaxPriority3 { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool VisibleOnInit { get { int o = __p.__offset(38); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }
  public bool OverrideLodCategory { get { int o = __p.__offset(40); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string LodCategory { get { int o = __p.__offset(42); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLodCategoryBytes() { return __p.__vector_as_span<byte>(42, 1); }
#else
  public ArraySegment<byte>? GetLodCategoryBytes() { return __p.__vector_as_arraysegment(42); }
#endif
  public byte[] GetLodCategoryArray() { return __p.__vector_as_array<byte>(42); }
  public string LodSubCategory { get { int o = __p.__offset(44); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLodSubCategoryBytes() { return __p.__vector_as_span<byte>(44, 1); }
#else
  public ArraySegment<byte>? GetLodSubCategoryBytes() { return __p.__vector_as_arraysegment(44); }
#endif
  public byte[] GetLodSubCategoryArray() { return __p.__vector_as_array<byte>(44); }
  public gfl.scene.fb.ModelLodOrigin LodOrigin { get { int o = __p.__offset(46); return o != 0 ? (gfl.scene.fb.ModelLodOrigin)__p.bb.GetSbyte(o + __p.bb_pos) : gfl.scene.fb.ModelLodOrigin.Object; } }
  public string OptNameSpace { get { int o = __p.__offset(48); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetOptNameSpaceBytes() { return __p.__vector_as_span<byte>(48, 1); }
#else
  public ArraySegment<byte>? GetOptNameSpaceBytes() { return __p.__vector_as_arraysegment(48); }
#endif
  public byte[] GetOptNameSpaceArray() { return __p.__vector_as_array<byte>(48); }
  public bool IsStatic { get { int o = __p.__offset(50); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<gfl.scene.fb.ModelComponent> CreateModelComponent(FlatBufferBuilder builder,
      StringOffset filePathOffset = default(StringOffset),
      StringOffset resourceNameOffset = default(StringOffset),
      StringOffset metaFilePathOffset = default(StringOffset),
      StringOffset metaItemNameOffset = default(StringOffset),
      bool overrideLodDistance = false,
      float lodDistance0 = 0.0f,
      float lodDistance1 = 0.0f,
      float lodDistance2 = 0.0f,
      bool jointPriorityEnabled = false,
      float jointPriorityDistance0 = 0.0f,
      int jointMaxPriority0 = 0,
      float jointPriorityDistance1 = 0.0f,
      int jointMaxPriority1 = 0,
      float jointPriorityDistance2 = 0.0f,
      int jointMaxPriority2 = 0,
      float jointPriorityDistance3 = 0.0f,
      int jointMaxPriority3 = 0,
      bool visibleOnInit = true,
      bool overrideLodCategory = false,
      StringOffset lodCategoryOffset = default(StringOffset),
      StringOffset lodSubCategoryOffset = default(StringOffset),
      gfl.scene.fb.ModelLodOrigin lodOrigin = gfl.scene.fb.ModelLodOrigin.Object,
      StringOffset optNameSpaceOffset = default(StringOffset),
      bool isStatic = false) {
    builder.StartTable(24);
    ModelComponent.AddOptNameSpace(builder, optNameSpaceOffset);
    ModelComponent.AddLodSubCategory(builder, lodSubCategoryOffset);
    ModelComponent.AddLodCategory(builder, lodCategoryOffset);
    ModelComponent.AddJointMaxPriority3(builder, jointMaxPriority3);
    ModelComponent.AddJointPriorityDistance3(builder, jointPriorityDistance3);
    ModelComponent.AddJointMaxPriority2(builder, jointMaxPriority2);
    ModelComponent.AddJointPriorityDistance2(builder, jointPriorityDistance2);
    ModelComponent.AddJointMaxPriority1(builder, jointMaxPriority1);
    ModelComponent.AddJointPriorityDistance1(builder, jointPriorityDistance1);
    ModelComponent.AddJointMaxPriority0(builder, jointMaxPriority0);
    ModelComponent.AddJointPriorityDistance0(builder, jointPriorityDistance0);
    ModelComponent.AddLodDistance2(builder, lodDistance2);
    ModelComponent.AddLodDistance1(builder, lodDistance1);
    ModelComponent.AddLodDistance0(builder, lodDistance0);
    ModelComponent.AddMetaItemName(builder, metaItemNameOffset);
    ModelComponent.AddMetaFilePath(builder, metaFilePathOffset);
    ModelComponent.AddResourceName(builder, resourceNameOffset);
    ModelComponent.AddFilePath(builder, filePathOffset);
    ModelComponent.AddIsStatic(builder, isStatic);
    ModelComponent.AddLodOrigin(builder, lodOrigin);
    ModelComponent.AddOverrideLodCategory(builder, overrideLodCategory);
    ModelComponent.AddVisibleOnInit(builder, visibleOnInit);
    ModelComponent.AddJointPriorityEnabled(builder, jointPriorityEnabled);
    ModelComponent.AddOverrideLodDistance(builder, overrideLodDistance);
    return ModelComponent.EndModelComponent(builder);
  }

  public static void StartModelComponent(FlatBufferBuilder builder) { builder.StartTable(24); }
  public static void AddFilePath(FlatBufferBuilder builder, StringOffset filePathOffset) { builder.AddOffset(0, filePathOffset.Value, 0); }
  public static void AddResourceName(FlatBufferBuilder builder, StringOffset resourceNameOffset) { builder.AddOffset(1, resourceNameOffset.Value, 0); }
  public static void AddMetaFilePath(FlatBufferBuilder builder, StringOffset metaFilePathOffset) { builder.AddOffset(2, metaFilePathOffset.Value, 0); }
  public static void AddMetaItemName(FlatBufferBuilder builder, StringOffset metaItemNameOffset) { builder.AddOffset(3, metaItemNameOffset.Value, 0); }
  public static void AddOverrideLodDistance(FlatBufferBuilder builder, bool overrideLodDistance) { builder.AddBool(4, overrideLodDistance, false); }
  public static void AddLodDistance0(FlatBufferBuilder builder, float lodDistance0) { builder.AddFloat(5, lodDistance0, 0.0f); }
  public static void AddLodDistance1(FlatBufferBuilder builder, float lodDistance1) { builder.AddFloat(6, lodDistance1, 0.0f); }
  public static void AddLodDistance2(FlatBufferBuilder builder, float lodDistance2) { builder.AddFloat(7, lodDistance2, 0.0f); }
  public static void AddJointPriorityEnabled(FlatBufferBuilder builder, bool jointPriorityEnabled) { builder.AddBool(8, jointPriorityEnabled, false); }
  public static void AddJointPriorityDistance0(FlatBufferBuilder builder, float jointPriorityDistance0) { builder.AddFloat(9, jointPriorityDistance0, 0.0f); }
  public static void AddJointMaxPriority0(FlatBufferBuilder builder, int jointMaxPriority0) { builder.AddInt(10, jointMaxPriority0, 0); }
  public static void AddJointPriorityDistance1(FlatBufferBuilder builder, float jointPriorityDistance1) { builder.AddFloat(11, jointPriorityDistance1, 0.0f); }
  public static void AddJointMaxPriority1(FlatBufferBuilder builder, int jointMaxPriority1) { builder.AddInt(12, jointMaxPriority1, 0); }
  public static void AddJointPriorityDistance2(FlatBufferBuilder builder, float jointPriorityDistance2) { builder.AddFloat(13, jointPriorityDistance2, 0.0f); }
  public static void AddJointMaxPriority2(FlatBufferBuilder builder, int jointMaxPriority2) { builder.AddInt(14, jointMaxPriority2, 0); }
  public static void AddJointPriorityDistance3(FlatBufferBuilder builder, float jointPriorityDistance3) { builder.AddFloat(15, jointPriorityDistance3, 0.0f); }
  public static void AddJointMaxPriority3(FlatBufferBuilder builder, int jointMaxPriority3) { builder.AddInt(16, jointMaxPriority3, 0); }
  public static void AddVisibleOnInit(FlatBufferBuilder builder, bool visibleOnInit) { builder.AddBool(17, visibleOnInit, true); }
  public static void AddOverrideLodCategory(FlatBufferBuilder builder, bool overrideLodCategory) { builder.AddBool(18, overrideLodCategory, false); }
  public static void AddLodCategory(FlatBufferBuilder builder, StringOffset lodCategoryOffset) { builder.AddOffset(19, lodCategoryOffset.Value, 0); }
  public static void AddLodSubCategory(FlatBufferBuilder builder, StringOffset lodSubCategoryOffset) { builder.AddOffset(20, lodSubCategoryOffset.Value, 0); }
  public static void AddLodOrigin(FlatBufferBuilder builder, gfl.scene.fb.ModelLodOrigin lodOrigin) { builder.AddSbyte(21, (sbyte)lodOrigin, 0); }
  public static void AddOptNameSpace(FlatBufferBuilder builder, StringOffset optNameSpaceOffset) { builder.AddOffset(22, optNameSpaceOffset.Value, 0); }
  public static void AddIsStatic(FlatBufferBuilder builder, bool isStatic) { builder.AddBool(23, isStatic, false); }
  public static Offset<gfl.scene.fb.ModelComponent> EndModelComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.ModelComponent>(o);
  }
  public static void FinishModelComponentBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.ModelComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedModelComponentBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.ModelComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public ModelComponentT UnPack() {
    var _o = new ModelComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ModelComponentT _o) {
    _o.FilePath = this.FilePath;
    _o.ResourceName = this.ResourceName;
    _o.MetaFilePath = this.MetaFilePath;
    _o.MetaItemName = this.MetaItemName;
    _o.OverrideLodDistance = this.OverrideLodDistance;
    _o.LodDistance0 = this.LodDistance0;
    _o.LodDistance1 = this.LodDistance1;
    _o.LodDistance2 = this.LodDistance2;
    _o.JointPriorityEnabled = this.JointPriorityEnabled;
    _o.JointPriorityDistance0 = this.JointPriorityDistance0;
    _o.JointMaxPriority0 = this.JointMaxPriority0;
    _o.JointPriorityDistance1 = this.JointPriorityDistance1;
    _o.JointMaxPriority1 = this.JointMaxPriority1;
    _o.JointPriorityDistance2 = this.JointPriorityDistance2;
    _o.JointMaxPriority2 = this.JointMaxPriority2;
    _o.JointPriorityDistance3 = this.JointPriorityDistance3;
    _o.JointMaxPriority3 = this.JointMaxPriority3;
    _o.VisibleOnInit = this.VisibleOnInit;
    _o.OverrideLodCategory = this.OverrideLodCategory;
    _o.LodCategory = this.LodCategory;
    _o.LodSubCategory = this.LodSubCategory;
    _o.LodOrigin = this.LodOrigin;
    _o.OptNameSpace = this.OptNameSpace;
    _o.IsStatic = this.IsStatic;
  }
  public static Offset<gfl.scene.fb.ModelComponent> Pack(FlatBufferBuilder builder, ModelComponentT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.ModelComponent>);
    var _filePath = _o.FilePath == null ? default(StringOffset) : builder.CreateString(_o.FilePath);
    var _resourceName = _o.ResourceName == null ? default(StringOffset) : builder.CreateString(_o.ResourceName);
    var _metaFilePath = _o.MetaFilePath == null ? default(StringOffset) : builder.CreateString(_o.MetaFilePath);
    var _metaItemName = _o.MetaItemName == null ? default(StringOffset) : builder.CreateString(_o.MetaItemName);
    var _lodCategory = _o.LodCategory == null ? default(StringOffset) : builder.CreateString(_o.LodCategory);
    var _lodSubCategory = _o.LodSubCategory == null ? default(StringOffset) : builder.CreateString(_o.LodSubCategory);
    var _optNameSpace = _o.OptNameSpace == null ? default(StringOffset) : builder.CreateString(_o.OptNameSpace);
    return CreateModelComponent(
      builder,
      _filePath,
      _resourceName,
      _metaFilePath,
      _metaItemName,
      _o.OverrideLodDistance,
      _o.LodDistance0,
      _o.LodDistance1,
      _o.LodDistance2,
      _o.JointPriorityEnabled,
      _o.JointPriorityDistance0,
      _o.JointMaxPriority0,
      _o.JointPriorityDistance1,
      _o.JointMaxPriority1,
      _o.JointPriorityDistance2,
      _o.JointMaxPriority2,
      _o.JointPriorityDistance3,
      _o.JointMaxPriority3,
      _o.VisibleOnInit,
      _o.OverrideLodCategory,
      _lodCategory,
      _lodSubCategory,
      _o.LodOrigin,
      _optNameSpace,
      _o.IsStatic);
  }
}

public class ModelComponentT
{
  public string FilePath { get; set; }
  public string ResourceName { get; set; }
  public string MetaFilePath { get; set; }
  public string MetaItemName { get; set; }
  public bool OverrideLodDistance { get; set; }
  public float LodDistance0 { get; set; }
  public float LodDistance1 { get; set; }
  public float LodDistance2 { get; set; }
  public bool JointPriorityEnabled { get; set; }
  public float JointPriorityDistance0 { get; set; }
  public int JointMaxPriority0 { get; set; }
  public float JointPriorityDistance1 { get; set; }
  public int JointMaxPriority1 { get; set; }
  public float JointPriorityDistance2 { get; set; }
  public int JointMaxPriority2 { get; set; }
  public float JointPriorityDistance3 { get; set; }
  public int JointMaxPriority3 { get; set; }
  public bool VisibleOnInit { get; set; }
  public bool OverrideLodCategory { get; set; }
  public string LodCategory { get; set; }
  public string LodSubCategory { get; set; }
  public gfl.scene.fb.ModelLodOrigin LodOrigin { get; set; }
  public string OptNameSpace { get; set; }
  public bool IsStatic { get; set; }

  public ModelComponentT() {
    this.FilePath = null;
    this.ResourceName = null;
    this.MetaFilePath = null;
    this.MetaItemName = null;
    this.OverrideLodDistance = false;
    this.LodDistance0 = 0.0f;
    this.LodDistance1 = 0.0f;
    this.LodDistance2 = 0.0f;
    this.JointPriorityEnabled = false;
    this.JointPriorityDistance0 = 0.0f;
    this.JointMaxPriority0 = 0;
    this.JointPriorityDistance1 = 0.0f;
    this.JointMaxPriority1 = 0;
    this.JointPriorityDistance2 = 0.0f;
    this.JointMaxPriority2 = 0;
    this.JointPriorityDistance3 = 0.0f;
    this.JointMaxPriority3 = 0;
    this.VisibleOnInit = true;
    this.OverrideLodCategory = false;
    this.LodCategory = null;
    this.LodSubCategory = null;
    this.LodOrigin = gfl.scene.fb.ModelLodOrigin.Object;
    this.OptNameSpace = null;
    this.IsStatic = false;
  }
  public static ModelComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return ModelComponent.GetRootAsModelComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    ModelComponent.FinishModelComponentBuffer(fbb, ModelComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
