// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

public enum MotionType : int
{
  Static = 0,
  Keyframed = 1,
  Dynamic = 2,
};


}
