// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PencilShape : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PencilShape GetRootAsPencilShape(ByteBuffer _bb) { return GetRootAsPencilShape(_bb, new PencilShape()); }
  public static PencilShape GetRootAsPencilShape(ByteBuffer _bb, PencilShape obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PencilShape __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gfl.math.fb.Vector3f? Pos { get { int o = __p.__offset(4); return o != 0 ? (gfl.math.fb.Vector3f?)(new gfl.math.fb.Vector3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Radius { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float CylinderHeight { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float TipHeight { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int SliceCount { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public gfl.math.fb.Vector3f? Rot { get { int o = __p.__offset(14); return o != 0 ? (gfl.math.fb.Vector3f?)(new gfl.math.fb.Vector3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static Offset<gfl.scene.fb.PencilShape> CreatePencilShape(FlatBufferBuilder builder,
      gfl.math.fb.Vector3fT pos = null,
      float radius = 0.0f,
      float cylinderHeight = 0.0f,
      float tipHeight = 0.0f,
      int sliceCount = 0,
      gfl.math.fb.Vector3fT rot = null) {
    builder.StartTable(6);
    PencilShape.AddRot(builder, gfl.math.fb.Vector3f.Pack(builder, rot));
    PencilShape.AddSliceCount(builder, sliceCount);
    PencilShape.AddTipHeight(builder, tipHeight);
    PencilShape.AddCylinderHeight(builder, cylinderHeight);
    PencilShape.AddRadius(builder, radius);
    PencilShape.AddPos(builder, gfl.math.fb.Vector3f.Pack(builder, pos));
    return PencilShape.EndPencilShape(builder);
  }

  public static void StartPencilShape(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddPos(FlatBufferBuilder builder, Offset<gfl.math.fb.Vector3f> posOffset) { builder.AddStruct(0, posOffset.Value, 0); }
  public static void AddRadius(FlatBufferBuilder builder, float radius) { builder.AddFloat(1, radius, 0.0f); }
  public static void AddCylinderHeight(FlatBufferBuilder builder, float cylinderHeight) { builder.AddFloat(2, cylinderHeight, 0.0f); }
  public static void AddTipHeight(FlatBufferBuilder builder, float tipHeight) { builder.AddFloat(3, tipHeight, 0.0f); }
  public static void AddSliceCount(FlatBufferBuilder builder, int sliceCount) { builder.AddInt(4, sliceCount, 0); }
  public static void AddRot(FlatBufferBuilder builder, Offset<gfl.math.fb.Vector3f> rotOffset) { builder.AddStruct(5, rotOffset.Value, 0); }
  public static Offset<gfl.scene.fb.PencilShape> EndPencilShape(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.PencilShape>(o);
  }
  public PencilShapeT UnPack() {
    var _o = new PencilShapeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PencilShapeT _o) {
    _o.Pos = this.Pos.HasValue ? this.Pos.Value.UnPack() : null;
    _o.Radius = this.Radius;
    _o.CylinderHeight = this.CylinderHeight;
    _o.TipHeight = this.TipHeight;
    _o.SliceCount = this.SliceCount;
    _o.Rot = this.Rot.HasValue ? this.Rot.Value.UnPack() : null;
  }
  public static Offset<gfl.scene.fb.PencilShape> Pack(FlatBufferBuilder builder, PencilShapeT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.PencilShape>);
    return CreatePencilShape(
      builder,
      _o.Pos,
      _o.Radius,
      _o.CylinderHeight,
      _o.TipHeight,
      _o.SliceCount,
      _o.Rot);
  }
}

public class PencilShapeT
{
  public gfl.math.fb.Vector3fT Pos { get; set; }
  public float Radius { get; set; }
  public float CylinderHeight { get; set; }
  public float TipHeight { get; set; }
  public int SliceCount { get; set; }
  public gfl.math.fb.Vector3fT Rot { get; set; }

  public PencilShapeT() {
    this.Pos = new gfl.math.fb.Vector3fT();
    this.Radius = 0.0f;
    this.CylinderHeight = 0.0f;
    this.TipHeight = 0.0f;
    this.SliceCount = 0;
    this.Rot = new gfl.math.fb.Vector3fT();
  }
}


}
