// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PointTree : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PointTree GetRootAsPointTree(ByteBuffer _bb) { return GetRootAsPointTree(_bb, new PointTree()); }
  public static PointTree GetRootAsPointTree(ByteBuffer _bb, PointTree obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PointTree __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gfl.scene.fb.ScenePoint? Point { get { int o = __p.__offset(4); return o != 0 ? (gfl.scene.fb.ScenePoint?)(new gfl.scene.fb.ScenePoint()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public gfl.scene.fb.PointElement? Elements(int j) { int o = __p.__offset(6); return o != 0 ? (gfl.scene.fb.PointElement?)(new gfl.scene.fb.PointElement()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ElementsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<gfl.scene.fb.PointTree> CreatePointTree(FlatBufferBuilder builder,
      Offset<gfl.scene.fb.ScenePoint> pointOffset = default(Offset<gfl.scene.fb.ScenePoint>),
      VectorOffset elementsOffset = default(VectorOffset)) {
    builder.StartTable(2);
    PointTree.AddElements(builder, elementsOffset);
    PointTree.AddPoint(builder, pointOffset);
    return PointTree.EndPointTree(builder);
  }

  public static void StartPointTree(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPoint(FlatBufferBuilder builder, Offset<gfl.scene.fb.ScenePoint> pointOffset) { builder.AddOffset(0, pointOffset.Value, 0); }
  public static void AddElements(FlatBufferBuilder builder, VectorOffset elementsOffset) { builder.AddOffset(1, elementsOffset.Value, 0); }
  public static VectorOffset CreateElementsVector(FlatBufferBuilder builder, Offset<gfl.scene.fb.PointElement>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateElementsVectorBlock(FlatBufferBuilder builder, Offset<gfl.scene.fb.PointElement>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateElementsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<gfl.scene.fb.PointElement>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateElementsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<gfl.scene.fb.PointElement>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartElementsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<gfl.scene.fb.PointTree> EndPointTree(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.PointTree>(o);
  }
  public PointTreeT UnPack() {
    var _o = new PointTreeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PointTreeT _o) {
    _o.Point = this.Point.HasValue ? this.Point.Value.UnPack() : null;
    _o.Elements = new List<gfl.scene.fb.PointElementT>();
    for (var _j = 0; _j < this.ElementsLength; ++_j) {_o.Elements.Add(this.Elements(_j).HasValue ? this.Elements(_j).Value.UnPack() : null);}
  }
  public static Offset<gfl.scene.fb.PointTree> Pack(FlatBufferBuilder builder, PointTreeT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.PointTree>);
    var _point = _o.Point == null ? default(Offset<gfl.scene.fb.ScenePoint>) : gfl.scene.fb.ScenePoint.Pack(builder, _o.Point);
    var _elements = default(VectorOffset);
    if (_o.Elements != null) {
      var __elements = new Offset<gfl.scene.fb.PointElement>[_o.Elements.Count];
      for (var _j = 0; _j < __elements.Length; ++_j) { __elements[_j] = gfl.scene.fb.PointElement.Pack(builder, _o.Elements[_j]); }
      _elements = CreateElementsVector(builder, __elements);
    }
    return CreatePointTree(
      builder,
      _point,
      _elements);
  }
}

public class PointTreeT
{
  public gfl.scene.fb.ScenePointT Point { get; set; }
  public List<gfl.scene.fb.PointElementT> Elements { get; set; }

  public PointTreeT() {
    this.Point = null;
    this.Elements = null;
  }
}


}
