// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

public enum ProjectionType : byte
{
  Perspective = 0,
  Ortho = 1,
};


}
