// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PropertySheet : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PropertySheet GetRootAsPropertySheet(ByteBuffer _bb) { return GetRootAsPropertySheet(_bb, new PropertySheet()); }
  public static PropertySheet GetRootAsPropertySheet(ByteBuffer _bb, PropertySheet obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PropertySheet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string SchemaName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSchemaNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSchemaNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSchemaNameArray() { return __p.__vector_as_array<byte>(4); }
  public string ResourceName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetResourceNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetResourceNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetResourceNameArray() { return __p.__vector_as_array<byte>(6); }
  public gfl.scene.fb.PSTable? Values(int j) { int o = __p.__offset(8); return o != 0 ? (gfl.scene.fb.PSTable?)(new gfl.scene.fb.PSTable()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ValuesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<gfl.scene.fb.PropertySheet> CreatePropertySheet(FlatBufferBuilder builder,
      StringOffset schemaNameOffset = default(StringOffset),
      StringOffset resourceNameOffset = default(StringOffset),
      VectorOffset valuesOffset = default(VectorOffset)) {
    builder.StartTable(3);
    PropertySheet.AddValues(builder, valuesOffset);
    PropertySheet.AddResourceName(builder, resourceNameOffset);
    PropertySheet.AddSchemaName(builder, schemaNameOffset);
    return PropertySheet.EndPropertySheet(builder);
  }

  public static void StartPropertySheet(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddSchemaName(FlatBufferBuilder builder, StringOffset schemaNameOffset) { builder.AddOffset(0, schemaNameOffset.Value, 0); }
  public static void AddResourceName(FlatBufferBuilder builder, StringOffset resourceNameOffset) { builder.AddOffset(1, resourceNameOffset.Value, 0); }
  public static void AddValues(FlatBufferBuilder builder, VectorOffset valuesOffset) { builder.AddOffset(2, valuesOffset.Value, 0); }
  public static VectorOffset CreateValuesVector(FlatBufferBuilder builder, Offset<gfl.scene.fb.PSTable>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, Offset<gfl.scene.fb.PSTable>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<gfl.scene.fb.PSTable>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<gfl.scene.fb.PSTable>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartValuesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<gfl.scene.fb.PropertySheet> EndPropertySheet(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.PropertySheet>(o);
  }
  public static void FinishPropertySheetBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.PropertySheet> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPropertySheetBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.PropertySheet> offset) { builder.FinishSizePrefixed(offset.Value); }
  public PropertySheetT UnPack() {
    var _o = new PropertySheetT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PropertySheetT _o) {
    _o.SchemaName = this.SchemaName;
    _o.ResourceName = this.ResourceName;
    _o.Values = new List<gfl.scene.fb.PSTableT>();
    for (var _j = 0; _j < this.ValuesLength; ++_j) {_o.Values.Add(this.Values(_j).HasValue ? this.Values(_j).Value.UnPack() : null);}
  }
  public static Offset<gfl.scene.fb.PropertySheet> Pack(FlatBufferBuilder builder, PropertySheetT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.PropertySheet>);
    var _schemaName = _o.SchemaName == null ? default(StringOffset) : builder.CreateString(_o.SchemaName);
    var _resourceName = _o.ResourceName == null ? default(StringOffset) : builder.CreateString(_o.ResourceName);
    var _values = default(VectorOffset);
    if (_o.Values != null) {
      var __values = new Offset<gfl.scene.fb.PSTable>[_o.Values.Count];
      for (var _j = 0; _j < __values.Length; ++_j) { __values[_j] = gfl.scene.fb.PSTable.Pack(builder, _o.Values[_j]); }
      _values = CreateValuesVector(builder, __values);
    }
    return CreatePropertySheet(
      builder,
      _schemaName,
      _resourceName,
      _values);
  }
}

public class PropertySheetT
{
  public string SchemaName { get; set; }
  public string ResourceName { get; set; }
  public List<gfl.scene.fb.PSTableT> Values { get; set; }

  public PropertySheetT() {
    this.SchemaName = null;
    this.ResourceName = null;
    this.Values = null;
  }
  public static PropertySheetT DeserializeFromBinary(byte[] fbBuffer) {
    return PropertySheet.GetRootAsPropertySheet(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    PropertySheet.FinishPropertySheetBuffer(fbb, PropertySheet.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
