// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PSDecimal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PSDecimal GetRootAsPSDecimal(ByteBuffer _bb) { return GetRootAsPSDecimal(_bb, new PSDecimal()); }
  public static PSDecimal GetRootAsPSDecimal(ByteBuffer _bb, PSDecimal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PSDecimal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Data { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public byte Size { get { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<gfl.scene.fb.PSDecimal> CreatePSDecimal(FlatBufferBuilder builder,
      double data = 0.0,
      byte size = 0) {
    builder.StartTable(2);
    PSDecimal.AddData(builder, data);
    PSDecimal.AddSize(builder, size);
    return PSDecimal.EndPSDecimal(builder);
  }

  public static void StartPSDecimal(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddData(FlatBufferBuilder builder, double data) { builder.AddDouble(0, data, 0.0); }
  public static void AddSize(FlatBufferBuilder builder, byte size) { builder.AddByte(1, size, 0); }
  public static Offset<gfl.scene.fb.PSDecimal> EndPSDecimal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.PSDecimal>(o);
  }
  public PSDecimalT UnPack() {
    var _o = new PSDecimalT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PSDecimalT _o) {
    _o.Data = this.Data;
    _o.Size = this.Size;
  }
  public static Offset<gfl.scene.fb.PSDecimal> Pack(FlatBufferBuilder builder, PSDecimalT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.PSDecimal>);
    return CreatePSDecimal(
      builder,
      _o.Data,
      _o.Size);
  }
}

public class PSDecimalT
{
  public double Data { get; set; }
  public byte Size { get; set; }

  public PSDecimalT() {
    this.Data = 0.0;
    this.Size = 0;
  }
}


}
