// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PSEnum : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PSEnum GetRootAsPSEnum(ByteBuffer _bb) { return GetRootAsPSEnum(_bb, new PSEnum()); }
  public static PSEnum GetRootAsPSEnum(ByteBuffer _bb, PSEnum obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PSEnum __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public int Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<gfl.scene.fb.PSEnum> CreatePSEnum(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      int value = 0) {
    builder.StartTable(2);
    PSEnum.AddValue(builder, value);
    PSEnum.AddName(builder, nameOffset);
    return PSEnum.EndPSEnum(builder);
  }

  public static void StartPSEnum(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, int value) { builder.AddInt(1, value, 0); }
  public static Offset<gfl.scene.fb.PSEnum> EndPSEnum(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.PSEnum>(o);
  }
  public PSEnumT UnPack() {
    var _o = new PSEnumT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PSEnumT _o) {
    _o.Name = this.Name;
    _o.Value = this.Value;
  }
  public static Offset<gfl.scene.fb.PSEnum> Pack(FlatBufferBuilder builder, PSEnumT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.PSEnum>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    return CreatePSEnum(
      builder,
      _name,
      _o.Value);
  }
}

public class PSEnumT
{
  public string Name { get; set; }
  public int Value { get; set; }

  public PSEnumT() {
    this.Name = null;
    this.Value = 0;
  }
}


}
