// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SceneObjectLayer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static SceneObjectLayer GetRootAsSceneObjectLayer(ByteBuffer _bb) { return GetRootAsSceneObjectLayer(_bb, new SceneObjectLayer()); }
  public static SceneObjectLayer GetRootAsSceneObjectLayer(ByteBuffer _bb, SceneObjectLayer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SceneObjectLayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Priority { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public gfl.math.fb.SRT? Srt { get { int o = __p.__offset(8); return o != 0 ? (gfl.math.fb.SRT?)(new gfl.math.fb.SRT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<gfl.scene.fb.SceneObjectLayer> CreateSceneObjectLayer(FlatBufferBuilder builder,
      int priority = 0,
      StringOffset nameOffset = default(StringOffset),
      Offset<gfl.math.fb.SRT> srtOffset = default(Offset<gfl.math.fb.SRT>)) {
    builder.StartTable(3);
    SceneObjectLayer.AddSrt(builder, srtOffset);
    SceneObjectLayer.AddName(builder, nameOffset);
    SceneObjectLayer.AddPriority(builder, priority);
    return SceneObjectLayer.EndSceneObjectLayer(builder);
  }

  public static void StartSceneObjectLayer(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPriority(FlatBufferBuilder builder, int priority) { builder.AddInt(0, priority, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddSrt(FlatBufferBuilder builder, Offset<gfl.math.fb.SRT> srtOffset) { builder.AddOffset(2, srtOffset.Value, 0); }
  public static Offset<gfl.scene.fb.SceneObjectLayer> EndSceneObjectLayer(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.SceneObjectLayer>(o);
  }
  public SceneObjectLayerT UnPack() {
    var _o = new SceneObjectLayerT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SceneObjectLayerT _o) {
    _o.Priority = this.Priority;
    _o.Name = this.Name;
    _o.Srt = this.Srt.HasValue ? this.Srt.Value.UnPack() : null;
  }
  public static Offset<gfl.scene.fb.SceneObjectLayer> Pack(FlatBufferBuilder builder, SceneObjectLayerT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.SceneObjectLayer>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _srt = _o.Srt == null ? default(Offset<gfl.math.fb.SRT>) : gfl.math.fb.SRT.Pack(builder, _o.Srt);
    return CreateSceneObjectLayer(
      builder,
      _o.Priority,
      _name,
      _srt);
  }
}

public class SceneObjectLayerT
{
  public int Priority { get; set; }
  public string Name { get; set; }
  public gfl.math.fb.SRTT Srt { get; set; }

  public SceneObjectLayerT() {
    this.Priority = 0;
    this.Name = null;
    this.Srt = null;
  }
}


}
