// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ScriptComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ScriptComponent GetRootAsScriptComponent(ByteBuffer _bb) { return GetRootAsScriptComponent(_bb, new ScriptComponent()); }
  public static ScriptComponent GetRootAsScriptComponent(ByteBuffer _bb, ScriptComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ScriptComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string FilePath { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilePathBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFilePathBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFilePathArray() { return __p.__vector_as_array<byte>(4); }
  public string PackageName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPackageNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPackageNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPackageNameArray() { return __p.__vector_as_array<byte>(6); }
  public bool IsParallelized { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float Priority { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public bool IsStatic { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ResourceName { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetResourceNameBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetResourceNameBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetResourceNameArray() { return __p.__vector_as_array<byte>(14); }

  public static Offset<gfl.scene.fb.ScriptComponent> CreateScriptComponent(FlatBufferBuilder builder,
      StringOffset filePathOffset = default(StringOffset),
      StringOffset packageNameOffset = default(StringOffset),
      bool isParallelized = false,
      float priority = 0.0f,
      bool isStatic = false,
      StringOffset resourceNameOffset = default(StringOffset)) {
    builder.StartTable(6);
    ScriptComponent.AddResourceName(builder, resourceNameOffset);
    ScriptComponent.AddPriority(builder, priority);
    ScriptComponent.AddPackageName(builder, packageNameOffset);
    ScriptComponent.AddFilePath(builder, filePathOffset);
    ScriptComponent.AddIsStatic(builder, isStatic);
    ScriptComponent.AddIsParallelized(builder, isParallelized);
    return ScriptComponent.EndScriptComponent(builder);
  }

  public static void StartScriptComponent(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddFilePath(FlatBufferBuilder builder, StringOffset filePathOffset) { builder.AddOffset(0, filePathOffset.Value, 0); }
  public static void AddPackageName(FlatBufferBuilder builder, StringOffset packageNameOffset) { builder.AddOffset(1, packageNameOffset.Value, 0); }
  public static void AddIsParallelized(FlatBufferBuilder builder, bool isParallelized) { builder.AddBool(2, isParallelized, false); }
  public static void AddPriority(FlatBufferBuilder builder, float priority) { builder.AddFloat(3, priority, 0.0f); }
  public static void AddIsStatic(FlatBufferBuilder builder, bool isStatic) { builder.AddBool(4, isStatic, false); }
  public static void AddResourceName(FlatBufferBuilder builder, StringOffset resourceNameOffset) { builder.AddOffset(5, resourceNameOffset.Value, 0); }
  public static Offset<gfl.scene.fb.ScriptComponent> EndScriptComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.ScriptComponent>(o);
  }
  public static void FinishScriptComponentBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.ScriptComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedScriptComponentBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.ScriptComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public ScriptComponentT UnPack() {
    var _o = new ScriptComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ScriptComponentT _o) {
    _o.FilePath = this.FilePath;
    _o.PackageName = this.PackageName;
    _o.IsParallelized = this.IsParallelized;
    _o.Priority = this.Priority;
    _o.IsStatic = this.IsStatic;
    _o.ResourceName = this.ResourceName;
  }
  public static Offset<gfl.scene.fb.ScriptComponent> Pack(FlatBufferBuilder builder, ScriptComponentT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.ScriptComponent>);
    var _filePath = _o.FilePath == null ? default(StringOffset) : builder.CreateString(_o.FilePath);
    var _packageName = _o.PackageName == null ? default(StringOffset) : builder.CreateString(_o.PackageName);
    var _resourceName = _o.ResourceName == null ? default(StringOffset) : builder.CreateString(_o.ResourceName);
    return CreateScriptComponent(
      builder,
      _filePath,
      _packageName,
      _o.IsParallelized,
      _o.Priority,
      _o.IsStatic,
      _resourceName);
  }
}

public class ScriptComponentT
{
  public string FilePath { get; set; }
  public string PackageName { get; set; }
  public bool IsParallelized { get; set; }
  public float Priority { get; set; }
  public bool IsStatic { get; set; }
  public string ResourceName { get; set; }

  public ScriptComponentT() {
    this.FilePath = null;
    this.PackageName = null;
    this.IsParallelized = false;
    this.Priority = 0.0f;
    this.IsStatic = false;
    this.ResourceName = null;
  }
  public static ScriptComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return ScriptComponent.GetRootAsScriptComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    ScriptComponent.FinishScriptComponentBuffer(fbb, ScriptComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
