// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SphereShape : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static SphereShape GetRootAsSphereShape(ByteBuffer _bb) { return GetRootAsSphereShape(_bb, new SphereShape()); }
  public static SphereShape GetRootAsSphereShape(ByteBuffer _bb, SphereShape obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SphereShape __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gfl.math.fb.Vector3f? Pos { get { int o = __p.__offset(4); return o != 0 ? (gfl.math.fb.Vector3f?)(new gfl.math.fb.Vector3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Radius { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<gfl.scene.fb.SphereShape> CreateSphereShape(FlatBufferBuilder builder,
      gfl.math.fb.Vector3fT pos = null,
      float radius = 0.0f) {
    builder.StartTable(2);
    SphereShape.AddRadius(builder, radius);
    SphereShape.AddPos(builder, gfl.math.fb.Vector3f.Pack(builder, pos));
    return SphereShape.EndSphereShape(builder);
  }

  public static void StartSphereShape(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPos(FlatBufferBuilder builder, Offset<gfl.math.fb.Vector3f> posOffset) { builder.AddStruct(0, posOffset.Value, 0); }
  public static void AddRadius(FlatBufferBuilder builder, float radius) { builder.AddFloat(1, radius, 0.0f); }
  public static Offset<gfl.scene.fb.SphereShape> EndSphereShape(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.SphereShape>(o);
  }
  public SphereShapeT UnPack() {
    var _o = new SphereShapeT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SphereShapeT _o) {
    _o.Pos = this.Pos.HasValue ? this.Pos.Value.UnPack() : null;
    _o.Radius = this.Radius;
  }
  public static Offset<gfl.scene.fb.SphereShape> Pack(FlatBufferBuilder builder, SphereShapeT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.SphereShape>);
    return CreateSphereShape(
      builder,
      _o.Pos,
      _o.Radius);
  }
}

public class SphereShapeT
{
  public gfl.math.fb.Vector3fT Pos { get; set; }
  public float Radius { get; set; }

  public SphereShapeT() {
    this.Pos = new gfl.math.fb.Vector3fT();
    this.Radius = 0.0f;
  }
}


}
