// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StreamingPoint : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static StreamingPoint GetRootAsStreamingPoint(ByteBuffer _bb) { return GetRootAsStreamingPoint(_bb, new StreamingPoint()); }
  public static StreamingPoint GetRootAsStreamingPoint(ByteBuffer _bb, StreamingPoint obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StreamingPoint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gfl.scene.fb.PointTree? Points(int j) { int o = __p.__offset(4); return o != 0 ? (gfl.scene.fb.PointTree?)(new gfl.scene.fb.PointTree()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PointsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<gfl.scene.fb.StreamingPoint> CreateStreamingPoint(FlatBufferBuilder builder,
      VectorOffset pointsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    StreamingPoint.AddPoints(builder, pointsOffset);
    return StreamingPoint.EndStreamingPoint(builder);
  }

  public static void StartStreamingPoint(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPoints(FlatBufferBuilder builder, VectorOffset pointsOffset) { builder.AddOffset(0, pointsOffset.Value, 0); }
  public static VectorOffset CreatePointsVector(FlatBufferBuilder builder, Offset<gfl.scene.fb.PointTree>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePointsVectorBlock(FlatBufferBuilder builder, Offset<gfl.scene.fb.PointTree>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePointsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<gfl.scene.fb.PointTree>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePointsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<gfl.scene.fb.PointTree>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPointsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<gfl.scene.fb.StreamingPoint> EndStreamingPoint(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.StreamingPoint>(o);
  }
  public static void FinishStreamingPointBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.StreamingPoint> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedStreamingPointBuffer(FlatBufferBuilder builder, Offset<gfl.scene.fb.StreamingPoint> offset) { builder.FinishSizePrefixed(offset.Value); }
  public StreamingPointT UnPack() {
    var _o = new StreamingPointT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(StreamingPointT _o) {
    _o.Points = new List<gfl.scene.fb.PointTreeT>();
    for (var _j = 0; _j < this.PointsLength; ++_j) {_o.Points.Add(this.Points(_j).HasValue ? this.Points(_j).Value.UnPack() : null);}
  }
  public static Offset<gfl.scene.fb.StreamingPoint> Pack(FlatBufferBuilder builder, StreamingPointT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.StreamingPoint>);
    var _points = default(VectorOffset);
    if (_o.Points != null) {
      var __points = new Offset<gfl.scene.fb.PointTree>[_o.Points.Count];
      for (var _j = 0; _j < __points.Length; ++_j) { __points[_j] = gfl.scene.fb.PointTree.Pack(builder, _o.Points[_j]); }
      _points = CreatePointsVector(builder, __points);
    }
    return CreateStreamingPoint(
      builder,
      _points);
  }
}

public class StreamingPointT
{
  public List<gfl.scene.fb.PointTreeT> Points { get; set; }

  public StreamingPointT() {
    this.Points = null;
  }
  public static StreamingPointT DeserializeFromBinary(byte[] fbBuffer) {
    return StreamingPoint.GetRootAsStreamingPoint(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    StreamingPoint.FinishStreamingPointBuffer(fbb, StreamingPoint.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
