// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.scene.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TrSceneChunk : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static TrSceneChunk GetRootAsTrSceneChunk(ByteBuffer _bb) { return GetRootAsTrSceneChunk(_bb, new TrSceneChunk()); }
  public static TrSceneChunk GetRootAsTrSceneChunk(ByteBuffer _bb, TrSceneChunk obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TrSceneChunk __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Type { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTypeBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetTypeBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetTypeArray() { return __p.__vector_as_array<byte>(4); }
  public byte Data(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int DataLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDataArray() { return __p.__vector_as_array<byte>(6); }
  public gfl.scene.fb.TrSceneChunk? Children(int j) { int o = __p.__offset(8); return o != 0 ? (gfl.scene.fb.TrSceneChunk?)(new gfl.scene.fb.TrSceneChunk()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChildrenLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<gfl.scene.fb.TrSceneChunk> CreateTrSceneChunk(FlatBufferBuilder builder,
      StringOffset typeOffset = default(StringOffset),
      VectorOffset dataOffset = default(VectorOffset),
      VectorOffset childrenOffset = default(VectorOffset)) {
    builder.StartTable(3);
    TrSceneChunk.AddChildren(builder, childrenOffset);
    TrSceneChunk.AddData(builder, dataOffset);
    TrSceneChunk.AddType(builder, typeOffset);
    return TrSceneChunk.EndTrSceneChunk(builder);
  }

  public static void StartTrSceneChunk(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddType(FlatBufferBuilder builder, StringOffset typeOffset) { builder.AddOffset(0, typeOffset.Value, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(1, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddChildren(FlatBufferBuilder builder, VectorOffset childrenOffset) { builder.AddOffset(2, childrenOffset.Value, 0); }
  public static VectorOffset CreateChildrenVector(FlatBufferBuilder builder, Offset<gfl.scene.fb.TrSceneChunk>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, Offset<gfl.scene.fb.TrSceneChunk>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<gfl.scene.fb.TrSceneChunk>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChildrenVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<gfl.scene.fb.TrSceneChunk>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChildrenVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<gfl.scene.fb.TrSceneChunk> EndTrSceneChunk(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.scene.fb.TrSceneChunk>(o);
  }
  public TrSceneChunkT UnPack() {
    var _o = new TrSceneChunkT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TrSceneChunkT _o) {
    _o.Type = this.Type;
    _o.Data = new List<byte>();
    for (var _j = 0; _j < this.DataLength; ++_j) {_o.Data.Add(this.Data(_j));}
    _o.Children = new List<gfl.scene.fb.TrSceneChunkT>();
    for (var _j = 0; _j < this.ChildrenLength; ++_j) {_o.Children.Add(this.Children(_j).HasValue ? this.Children(_j).Value.UnPack() : null);}
  }
  public static Offset<gfl.scene.fb.TrSceneChunk> Pack(FlatBufferBuilder builder, TrSceneChunkT _o) {
    if (_o == null) return default(Offset<gfl.scene.fb.TrSceneChunk>);
    var _type = _o.Type == null ? default(StringOffset) : builder.CreateString(_o.Type);
    var _data = default(VectorOffset);
    if (_o.Data != null) {
      var __data = _o.Data.ToArray();
      _data = CreateDataVector(builder, __data);
    }
    var _children = default(VectorOffset);
    if (_o.Children != null) {
      var __children = new Offset<gfl.scene.fb.TrSceneChunk>[_o.Children.Count];
      for (var _j = 0; _j < __children.Length; ++_j) { __children[_j] = gfl.scene.fb.TrSceneChunk.Pack(builder, _o.Children[_j]); }
      _children = CreateChildrenVector(builder, __children);
    }
    return CreateTrSceneChunk(
      builder,
      _type,
      _data,
      _children);
  }
}

public class TrSceneChunkT
{
  public string Type { get; set; }
  public List<byte> Data { get; set; }
  public List<gfl.scene.fb.TrSceneChunkT> Children { get; set; }

  public TrSceneChunkT() {
    this.Type = null;
    this.Data = null;
    this.Children = null;
  }
}


}
