// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct data_table : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static data_table GetRootAsdata_table(ByteBuffer _bb) { return GetRootAsdata_table(_bb, new data_table()); }
  public static data_table GetRootAsdata_table(ByteBuffer _bb, data_table obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public data_table __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string KeyName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetKeyNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetKeyNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetKeyNameArray() { return __p.__vector_as_array<byte>(4); }
  public string FilePath { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilePathBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetFilePathBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetFilePathArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<Titan.TrinityScene.data_table> Createdata_table(FlatBufferBuilder builder,
      StringOffset Key_NameOffset = default(StringOffset),
      StringOffset File_pathOffset = default(StringOffset)) {
    builder.StartTable(2);
    data_table.AddFilePath(builder, File_pathOffset);
    data_table.AddKeyName(builder, Key_NameOffset);
    return data_table.Enddata_table(builder);
  }

  public static void Startdata_table(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddKeyName(FlatBufferBuilder builder, StringOffset KeyNameOffset) { builder.AddOffset(0, KeyNameOffset.Value, 0); }
  public static void AddFilePath(FlatBufferBuilder builder, StringOffset FilePathOffset) { builder.AddOffset(1, FilePathOffset.Value, 0); }
  public static Offset<Titan.TrinityScene.data_table> Enddata_table(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.data_table>(o);
  }
  public data_tableT UnPack() {
    var _o = new data_tableT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(data_tableT _o) {
    _o.KeyName = this.KeyName;
    _o.FilePath = this.FilePath;
  }
  public static Offset<Titan.TrinityScene.data_table> Pack(FlatBufferBuilder builder, data_tableT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.data_table>);
    var _Key_Name = _o.KeyName == null ? default(StringOffset) : builder.CreateString(_o.KeyName);
    var _File_path = _o.FilePath == null ? default(StringOffset) : builder.CreateString(_o.FilePath);
    return Createdata_table(
      builder,
      _Key_Name,
      _File_path);
  }
}

public class data_tableT
{
  public string KeyName { get; set; }
  public string FilePath { get; set; }

  public data_tableT() {
    this.KeyName = null;
    this.FilePath = null;
  }
}

public struct pe_FlatbuffersDataComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static pe_FlatbuffersDataComponent GetRootAspe_FlatbuffersDataComponent(ByteBuffer _bb) { return GetRootAspe_FlatbuffersDataComponent(_bb, new pe_FlatbuffersDataComponent()); }
  public static pe_FlatbuffersDataComponent GetRootAspe_FlatbuffersDataComponent(ByteBuffer _bb, pe_FlatbuffersDataComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public pe_FlatbuffersDataComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string BfbsFilePath { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBfbsFilePathBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetBfbsFilePathBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetBfbsFilePathArray() { return __p.__vector_as_array<byte>(4); }
  public Titan.TrinityScene.data_table? DataTableList(int j) { int o = __p.__offset(6); return o != 0 ? (Titan.TrinityScene.data_table?)(new Titan.TrinityScene.data_table()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataTableListLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Titan.TrinityScene.pe_FlatbuffersDataComponent> Createpe_FlatbuffersDataComponent(FlatBufferBuilder builder,
      StringOffset bfbs_file_pathOffset = default(StringOffset),
      VectorOffset Data_table_listOffset = default(VectorOffset)) {
    builder.StartTable(2);
    pe_FlatbuffersDataComponent.AddDataTableList(builder, Data_table_listOffset);
    pe_FlatbuffersDataComponent.AddBfbsFilePath(builder, bfbs_file_pathOffset);
    return pe_FlatbuffersDataComponent.Endpe_FlatbuffersDataComponent(builder);
  }

  public static void Startpe_FlatbuffersDataComponent(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddBfbsFilePath(FlatBufferBuilder builder, StringOffset bfbsFilePathOffset) { builder.AddOffset(0, bfbsFilePathOffset.Value, 0); }
  public static void AddDataTableList(FlatBufferBuilder builder, VectorOffset DataTableListOffset) { builder.AddOffset(1, DataTableListOffset.Value, 0); }
  public static VectorOffset CreateDataTableListVector(FlatBufferBuilder builder, Offset<Titan.TrinityScene.data_table>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataTableListVectorBlock(FlatBufferBuilder builder, Offset<Titan.TrinityScene.data_table>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataTableListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Titan.TrinityScene.data_table>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataTableListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Titan.TrinityScene.data_table>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataTableListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Titan.TrinityScene.pe_FlatbuffersDataComponent> Endpe_FlatbuffersDataComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.pe_FlatbuffersDataComponent>(o);
  }
  public static void Finishpe_FlatbuffersDataComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.pe_FlatbuffersDataComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedpe_FlatbuffersDataComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.pe_FlatbuffersDataComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public pe_FlatbuffersDataComponentT UnPack() {
    var _o = new pe_FlatbuffersDataComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(pe_FlatbuffersDataComponentT _o) {
    _o.BfbsFilePath = this.BfbsFilePath;
    _o.DataTableList = new List<Titan.TrinityScene.data_tableT>();
    for (var _j = 0; _j < this.DataTableListLength; ++_j) {_o.DataTableList.Add(this.DataTableList(_j).HasValue ? this.DataTableList(_j).Value.UnPack() : null);}
  }
  public static Offset<Titan.TrinityScene.pe_FlatbuffersDataComponent> Pack(FlatBufferBuilder builder, pe_FlatbuffersDataComponentT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.pe_FlatbuffersDataComponent>);
    var _bfbs_file_path = _o.BfbsFilePath == null ? default(StringOffset) : builder.CreateString(_o.BfbsFilePath);
    var _Data_table_list = default(VectorOffset);
    if (_o.DataTableList != null) {
      var __Data_table_list = new Offset<Titan.TrinityScene.data_table>[_o.DataTableList.Count];
      for (var _j = 0; _j < __Data_table_list.Length; ++_j) { __Data_table_list[_j] = Titan.TrinityScene.data_table.Pack(builder, _o.DataTableList[_j]); }
      _Data_table_list = CreateDataTableListVector(builder, __Data_table_list);
    }
    return Createpe_FlatbuffersDataComponent(
      builder,
      _bfbs_file_path,
      _Data_table_list);
  }
}

public class pe_FlatbuffersDataComponentT
{
  public string BfbsFilePath { get; set; }
  public List<Titan.TrinityScene.data_tableT> DataTableList { get; set; }

  public pe_FlatbuffersDataComponentT() {
    this.BfbsFilePath = null;
    this.DataTableList = null;
  }
  public static pe_FlatbuffersDataComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return pe_FlatbuffersDataComponent.GetRootAspe_FlatbuffersDataComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    pe_FlatbuffersDataComponent.Finishpe_FlatbuffersDataComponentBuffer(fbb, pe_FlatbuffersDataComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
