// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ietc_data : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ietc_data GetRootAsietc_data(ByteBuffer _bb) { return GetRootAsietc_data(_bb, new ietc_data()); }
  public static ietc_data GetRootAsietc_data(ByteBuffer _bb, ietc_data obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ietc_data __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void Startietc_data(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Titan.TrinityScene.ietc_data> Endietc_data(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.ietc_data>(o);
  }
  public ietc_dataT UnPack() {
    var _o = new ietc_dataT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ietc_dataT _o) {
  }
  public static Offset<Titan.TrinityScene.ietc_data> Pack(FlatBufferBuilder builder, ietc_dataT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.ietc_data>);
    Startietc_data(builder);
    return Endietc_data(builder);
  }
}

public class ietc_dataT
{

  public ietc_dataT() {
  }
}

public struct pe_InputEventTriggerComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static pe_InputEventTriggerComponent GetRootAspe_InputEventTriggerComponent(ByteBuffer _bb) { return GetRootAspe_InputEventTriggerComponent(_bb, new pe_InputEventTriggerComponent()); }
  public static pe_InputEventTriggerComponent GetRootAspe_InputEventTriggerComponent(ByteBuffer _bb, pe_InputEventTriggerComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public pe_InputEventTriggerComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Unk0 { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnk0Bytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUnk0Bytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUnk0Array() { return __p.__vector_as_array<byte>(4); }
  public string Unk1 { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnk1Bytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUnk1Bytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUnk1Array() { return __p.__vector_as_array<byte>(6); }
  public uint Unk2 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Unk3 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Unk4 { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnk4Bytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetUnk4Bytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetUnk4Array() { return __p.__vector_as_array<byte>(12); }
  public Titan.TrinityScene.ietc_data? Unk5(int j) { int o = __p.__offset(14); return o != 0 ? (Titan.TrinityScene.ietc_data?)(new Titan.TrinityScene.ietc_data()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Unk5Length { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Titan.TrinityScene.pe_InputEventTriggerComponent> Createpe_InputEventTriggerComponent(FlatBufferBuilder builder,
      StringOffset unk_0Offset = default(StringOffset),
      StringOffset unk_1Offset = default(StringOffset),
      uint unk_2 = 0,
      uint unk_3 = 0,
      StringOffset unk_4Offset = default(StringOffset),
      VectorOffset unk_5Offset = default(VectorOffset)) {
    builder.StartTable(6);
    pe_InputEventTriggerComponent.AddUnk5(builder, unk_5Offset);
    pe_InputEventTriggerComponent.AddUnk4(builder, unk_4Offset);
    pe_InputEventTriggerComponent.AddUnk3(builder, unk_3);
    pe_InputEventTriggerComponent.AddUnk2(builder, unk_2);
    pe_InputEventTriggerComponent.AddUnk1(builder, unk_1Offset);
    pe_InputEventTriggerComponent.AddUnk0(builder, unk_0Offset);
    return pe_InputEventTriggerComponent.Endpe_InputEventTriggerComponent(builder);
  }

  public static void Startpe_InputEventTriggerComponent(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddUnk0(FlatBufferBuilder builder, StringOffset unk0Offset) { builder.AddOffset(0, unk0Offset.Value, 0); }
  public static void AddUnk1(FlatBufferBuilder builder, StringOffset unk1Offset) { builder.AddOffset(1, unk1Offset.Value, 0); }
  public static void AddUnk2(FlatBufferBuilder builder, uint unk2) { builder.AddUint(2, unk2, 0); }
  public static void AddUnk3(FlatBufferBuilder builder, uint unk3) { builder.AddUint(3, unk3, 0); }
  public static void AddUnk4(FlatBufferBuilder builder, StringOffset unk4Offset) { builder.AddOffset(4, unk4Offset.Value, 0); }
  public static void AddUnk5(FlatBufferBuilder builder, VectorOffset unk5Offset) { builder.AddOffset(5, unk5Offset.Value, 0); }
  public static VectorOffset CreateUnk5Vector(FlatBufferBuilder builder, Offset<Titan.TrinityScene.ietc_data>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateUnk5VectorBlock(FlatBufferBuilder builder, Offset<Titan.TrinityScene.ietc_data>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnk5VectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Titan.TrinityScene.ietc_data>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnk5VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Titan.TrinityScene.ietc_data>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUnk5Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Titan.TrinityScene.pe_InputEventTriggerComponent> Endpe_InputEventTriggerComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.pe_InputEventTriggerComponent>(o);
  }
  public static void Finishpe_InputEventTriggerComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.pe_InputEventTriggerComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedpe_InputEventTriggerComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.pe_InputEventTriggerComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public pe_InputEventTriggerComponentT UnPack() {
    var _o = new pe_InputEventTriggerComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(pe_InputEventTriggerComponentT _o) {
    _o.Unk0 = this.Unk0;
    _o.Unk1 = this.Unk1;
    _o.Unk2 = this.Unk2;
    _o.Unk3 = this.Unk3;
    _o.Unk4 = this.Unk4;
    _o.Unk5 = new List<Titan.TrinityScene.ietc_dataT>();
    for (var _j = 0; _j < this.Unk5Length; ++_j) {_o.Unk5.Add(this.Unk5(_j).HasValue ? this.Unk5(_j).Value.UnPack() : null);}
  }
  public static Offset<Titan.TrinityScene.pe_InputEventTriggerComponent> Pack(FlatBufferBuilder builder, pe_InputEventTriggerComponentT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.pe_InputEventTriggerComponent>);
    var _unk_0 = _o.Unk0 == null ? default(StringOffset) : builder.CreateString(_o.Unk0);
    var _unk_1 = _o.Unk1 == null ? default(StringOffset) : builder.CreateString(_o.Unk1);
    var _unk_4 = _o.Unk4 == null ? default(StringOffset) : builder.CreateString(_o.Unk4);
    var _unk_5 = default(VectorOffset);
    if (_o.Unk5 != null) {
      var __unk_5 = new Offset<Titan.TrinityScene.ietc_data>[_o.Unk5.Count];
      for (var _j = 0; _j < __unk_5.Length; ++_j) { __unk_5[_j] = Titan.TrinityScene.ietc_data.Pack(builder, _o.Unk5[_j]); }
      _unk_5 = CreateUnk5Vector(builder, __unk_5);
    }
    return Createpe_InputEventTriggerComponent(
      builder,
      _unk_0,
      _unk_1,
      _o.Unk2,
      _o.Unk3,
      _unk_4,
      _unk_5);
  }
}

public class pe_InputEventTriggerComponentT
{
  public string Unk0 { get; set; }
  public string Unk1 { get; set; }
  public uint Unk2 { get; set; }
  public uint Unk3 { get; set; }
  public string Unk4 { get; set; }
  public List<Titan.TrinityScene.ietc_dataT> Unk5 { get; set; }

  public pe_InputEventTriggerComponentT() {
    this.Unk0 = null;
    this.Unk1 = null;
    this.Unk2 = 0;
    this.Unk3 = 0;
    this.Unk4 = null;
    this.Unk5 = null;
  }
  public static pe_InputEventTriggerComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return pe_InputEventTriggerComponent.GetRootAspe_InputEventTriggerComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    pe_InputEventTriggerComponent.Finishpe_InputEventTriggerComponentBuffer(fbb, pe_InputEventTriggerComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
