// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct pe_ParticleAudioComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static pe_ParticleAudioComponent GetRootAspe_ParticleAudioComponent(ByteBuffer _bb) { return GetRootAspe_ParticleAudioComponent(_bb, new pe_ParticleAudioComponent()); }
  public static pe_ParticleAudioComponent GetRootAspe_ParticleAudioComponent(ByteBuffer _bb, pe_ParticleAudioComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public pe_ParticleAudioComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Unk0 { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnk0Bytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUnk0Bytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUnk0Array() { return __p.__vector_as_array<byte>(4); }
  public string Unk1 { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnk1Bytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUnk1Bytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUnk1Array() { return __p.__vector_as_array<byte>(6); }
  public bool Unk2 { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool Unk3 { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Titan.TrinityScene.pe_ParticleAudioComponent> Createpe_ParticleAudioComponent(FlatBufferBuilder builder,
      StringOffset unk_0Offset = default(StringOffset),
      StringOffset unk_1Offset = default(StringOffset),
      bool unk_2 = false,
      bool unk_3 = false) {
    builder.StartTable(4);
    pe_ParticleAudioComponent.AddUnk1(builder, unk_1Offset);
    pe_ParticleAudioComponent.AddUnk0(builder, unk_0Offset);
    pe_ParticleAudioComponent.AddUnk3(builder, unk_3);
    pe_ParticleAudioComponent.AddUnk2(builder, unk_2);
    return pe_ParticleAudioComponent.Endpe_ParticleAudioComponent(builder);
  }

  public static void Startpe_ParticleAudioComponent(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddUnk0(FlatBufferBuilder builder, StringOffset unk0Offset) { builder.AddOffset(0, unk0Offset.Value, 0); }
  public static void AddUnk1(FlatBufferBuilder builder, StringOffset unk1Offset) { builder.AddOffset(1, unk1Offset.Value, 0); }
  public static void AddUnk2(FlatBufferBuilder builder, bool unk2) { builder.AddBool(2, unk2, false); }
  public static void AddUnk3(FlatBufferBuilder builder, bool unk3) { builder.AddBool(3, unk3, false); }
  public static Offset<Titan.TrinityScene.pe_ParticleAudioComponent> Endpe_ParticleAudioComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.pe_ParticleAudioComponent>(o);
  }
  public static void Finishpe_ParticleAudioComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.pe_ParticleAudioComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedpe_ParticleAudioComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.pe_ParticleAudioComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public pe_ParticleAudioComponentT UnPack() {
    var _o = new pe_ParticleAudioComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(pe_ParticleAudioComponentT _o) {
    _o.Unk0 = this.Unk0;
    _o.Unk1 = this.Unk1;
    _o.Unk2 = this.Unk2;
    _o.Unk3 = this.Unk3;
  }
  public static Offset<Titan.TrinityScene.pe_ParticleAudioComponent> Pack(FlatBufferBuilder builder, pe_ParticleAudioComponentT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.pe_ParticleAudioComponent>);
    var _unk_0 = _o.Unk0 == null ? default(StringOffset) : builder.CreateString(_o.Unk0);
    var _unk_1 = _o.Unk1 == null ? default(StringOffset) : builder.CreateString(_o.Unk1);
    return Createpe_ParticleAudioComponent(
      builder,
      _unk_0,
      _unk_1,
      _o.Unk2,
      _o.Unk3);
  }
}

public class pe_ParticleAudioComponentT
{
  public string Unk0 { get; set; }
  public string Unk1 { get; set; }
  public bool Unk2 { get; set; }
  public bool Unk3 { get; set; }

  public pe_ParticleAudioComponentT() {
    this.Unk0 = null;
    this.Unk1 = null;
    this.Unk2 = false;
    this.Unk3 = false;
  }
  public static pe_ParticleAudioComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return pe_ParticleAudioComponent.GetRootAspe_ParticleAudioComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    pe_ParticleAudioComponent.Finishpe_ParticleAudioComponentBuffer(fbb, pe_ParticleAudioComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
