// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct umc_data_1 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static umc_data_1 GetRootAsumc_data_1(ByteBuffer _bb) { return GetRootAsumc_data_1(_bb, new umc_data_1()); }
  public static umc_data_1 GetRootAsumc_data_1(ByteBuffer _bb, umc_data_1 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public umc_data_1 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void Startumc_data_1(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Titan.TrinityScene.umc_data_1> Endumc_data_1(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.umc_data_1>(o);
  }
  public umc_data_1T UnPack() {
    var _o = new umc_data_1T();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(umc_data_1T _o) {
  }
  public static Offset<Titan.TrinityScene.umc_data_1> Pack(FlatBufferBuilder builder, umc_data_1T _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.umc_data_1>);
    Startumc_data_1(builder);
    return Endumc_data_1(builder);
  }
}

public class umc_data_1T
{

  public umc_data_1T() {
  }
}

public struct umc_data_2 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static umc_data_2 GetRootAsumc_data_2(ByteBuffer _bb) { return GetRootAsumc_data_2(_bb, new umc_data_2()); }
  public static umc_data_2 GetRootAsumc_data_2(ByteBuffer _bb, umc_data_2 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public umc_data_2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void Startumc_data_2(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Titan.TrinityScene.umc_data_2> Endumc_data_2(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.umc_data_2>(o);
  }
  public umc_data_2T UnPack() {
    var _o = new umc_data_2T();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(umc_data_2T _o) {
  }
  public static Offset<Titan.TrinityScene.umc_data_2> Pack(FlatBufferBuilder builder, umc_data_2T _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.umc_data_2>);
    Startumc_data_2(builder);
    return Endumc_data_2(builder);
  }
}

public class umc_data_2T
{

  public umc_data_2T() {
  }
}

public struct pe_UikitManagerComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static pe_UikitManagerComponent GetRootAspe_UikitManagerComponent(ByteBuffer _bb) { return GetRootAspe_UikitManagerComponent(_bb, new pe_UikitManagerComponent()); }
  public static pe_UikitManagerComponent GetRootAspe_UikitManagerComponent(ByteBuffer _bb, pe_UikitManagerComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public pe_UikitManagerComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Filepath { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilepathBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFilepathBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFilepathArray() { return __p.__vector_as_array<byte>(4); }
  public uint Unk1 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Unk2 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public Titan.TrinityScene.umc_data_1? Unk3(int j) { int o = __p.__offset(10); return o != 0 ? (Titan.TrinityScene.umc_data_1?)(new Titan.TrinityScene.umc_data_1()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Unk3Length { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Titan.TrinityScene.umc_data_2? Unk4(int j) { int o = __p.__offset(12); return o != 0 ? (Titan.TrinityScene.umc_data_2?)(new Titan.TrinityScene.umc_data_2()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int Unk4Length { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Titan.TrinityScene.pe_UikitManagerComponent> Createpe_UikitManagerComponent(FlatBufferBuilder builder,
      StringOffset filepathOffset = default(StringOffset),
      uint unk_1 = 0,
      uint unk_2 = 0,
      VectorOffset unk_3Offset = default(VectorOffset),
      VectorOffset unk_4Offset = default(VectorOffset)) {
    builder.StartTable(5);
    pe_UikitManagerComponent.AddUnk4(builder, unk_4Offset);
    pe_UikitManagerComponent.AddUnk3(builder, unk_3Offset);
    pe_UikitManagerComponent.AddUnk2(builder, unk_2);
    pe_UikitManagerComponent.AddUnk1(builder, unk_1);
    pe_UikitManagerComponent.AddFilepath(builder, filepathOffset);
    return pe_UikitManagerComponent.Endpe_UikitManagerComponent(builder);
  }

  public static void Startpe_UikitManagerComponent(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddFilepath(FlatBufferBuilder builder, StringOffset filepathOffset) { builder.AddOffset(0, filepathOffset.Value, 0); }
  public static void AddUnk1(FlatBufferBuilder builder, uint unk1) { builder.AddUint(1, unk1, 0); }
  public static void AddUnk2(FlatBufferBuilder builder, uint unk2) { builder.AddUint(2, unk2, 0); }
  public static void AddUnk3(FlatBufferBuilder builder, VectorOffset unk3Offset) { builder.AddOffset(3, unk3Offset.Value, 0); }
  public static VectorOffset CreateUnk3Vector(FlatBufferBuilder builder, Offset<Titan.TrinityScene.umc_data_1>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateUnk3VectorBlock(FlatBufferBuilder builder, Offset<Titan.TrinityScene.umc_data_1>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnk3VectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Titan.TrinityScene.umc_data_1>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnk3VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Titan.TrinityScene.umc_data_1>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUnk3Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddUnk4(FlatBufferBuilder builder, VectorOffset unk4Offset) { builder.AddOffset(4, unk4Offset.Value, 0); }
  public static VectorOffset CreateUnk4Vector(FlatBufferBuilder builder, Offset<Titan.TrinityScene.umc_data_2>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateUnk4VectorBlock(FlatBufferBuilder builder, Offset<Titan.TrinityScene.umc_data_2>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnk4VectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Titan.TrinityScene.umc_data_2>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUnk4VectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Titan.TrinityScene.umc_data_2>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUnk4Vector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Titan.TrinityScene.pe_UikitManagerComponent> Endpe_UikitManagerComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.pe_UikitManagerComponent>(o);
  }
  public static void Finishpe_UikitManagerComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.pe_UikitManagerComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedpe_UikitManagerComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.pe_UikitManagerComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public pe_UikitManagerComponentT UnPack() {
    var _o = new pe_UikitManagerComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(pe_UikitManagerComponentT _o) {
    _o.Filepath = this.Filepath;
    _o.Unk1 = this.Unk1;
    _o.Unk2 = this.Unk2;
    _o.Unk3 = new List<Titan.TrinityScene.umc_data_1T>();
    for (var _j = 0; _j < this.Unk3Length; ++_j) {_o.Unk3.Add(this.Unk3(_j).HasValue ? this.Unk3(_j).Value.UnPack() : null);}
    _o.Unk4 = new List<Titan.TrinityScene.umc_data_2T>();
    for (var _j = 0; _j < this.Unk4Length; ++_j) {_o.Unk4.Add(this.Unk4(_j).HasValue ? this.Unk4(_j).Value.UnPack() : null);}
  }
  public static Offset<Titan.TrinityScene.pe_UikitManagerComponent> Pack(FlatBufferBuilder builder, pe_UikitManagerComponentT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.pe_UikitManagerComponent>);
    var _filepath = _o.Filepath == null ? default(StringOffset) : builder.CreateString(_o.Filepath);
    var _unk_3 = default(VectorOffset);
    if (_o.Unk3 != null) {
      var __unk_3 = new Offset<Titan.TrinityScene.umc_data_1>[_o.Unk3.Count];
      for (var _j = 0; _j < __unk_3.Length; ++_j) { __unk_3[_j] = Titan.TrinityScene.umc_data_1.Pack(builder, _o.Unk3[_j]); }
      _unk_3 = CreateUnk3Vector(builder, __unk_3);
    }
    var _unk_4 = default(VectorOffset);
    if (_o.Unk4 != null) {
      var __unk_4 = new Offset<Titan.TrinityScene.umc_data_2>[_o.Unk4.Count];
      for (var _j = 0; _j < __unk_4.Length; ++_j) { __unk_4[_j] = Titan.TrinityScene.umc_data_2.Pack(builder, _o.Unk4[_j]); }
      _unk_4 = CreateUnk4Vector(builder, __unk_4);
    }
    return Createpe_UikitManagerComponent(
      builder,
      _filepath,
      _o.Unk1,
      _o.Unk2,
      _unk_3,
      _unk_4);
  }
}

public class pe_UikitManagerComponentT
{
  public string Filepath { get; set; }
  public uint Unk1 { get; set; }
  public uint Unk2 { get; set; }
  public List<Titan.TrinityScene.umc_data_1T> Unk3 { get; set; }
  public List<Titan.TrinityScene.umc_data_2T> Unk4 { get; set; }

  public pe_UikitManagerComponentT() {
    this.Filepath = null;
    this.Unk1 = 0;
    this.Unk2 = 0;
    this.Unk3 = null;
    this.Unk4 = null;
  }
  public static pe_UikitManagerComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return pe_UikitManagerComponent.GetRootAspe_UikitManagerComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    pe_UikitManagerComponent.Finishpe_UikitManagerComponentBuffer(fbb, pe_UikitManagerComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
