// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ti_EnvSoundComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ti_EnvSoundComponent GetRootAsti_EnvSoundComponent(ByteBuffer _bb) { return GetRootAsti_EnvSoundComponent(_bb, new ti_EnvSoundComponent()); }
  public static ti_EnvSoundComponent GetRootAsti_EnvSoundComponent(ByteBuffer _bb, ti_EnvSoundComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ti_EnvSoundComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Titan.TrinityScene.ti_EnvSoundComponent> Createti_EnvSoundComponent(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(1);
    ti_EnvSoundComponent.AddName(builder, nameOffset);
    return ti_EnvSoundComponent.Endti_EnvSoundComponent(builder);
  }

  public static void Startti_EnvSoundComponent(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static Offset<Titan.TrinityScene.ti_EnvSoundComponent> Endti_EnvSoundComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.ti_EnvSoundComponent>(o);
  }
  public static void Finishti_EnvSoundComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.ti_EnvSoundComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedti_EnvSoundComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.ti_EnvSoundComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public ti_EnvSoundComponentT UnPack() {
    var _o = new ti_EnvSoundComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ti_EnvSoundComponentT _o) {
    _o.Name = this.Name;
  }
  public static Offset<Titan.TrinityScene.ti_EnvSoundComponent> Pack(FlatBufferBuilder builder, ti_EnvSoundComponentT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.ti_EnvSoundComponent>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    return Createti_EnvSoundComponent(
      builder,
      _name);
  }
}

public class ti_EnvSoundComponentT
{
  public string Name { get; set; }

  public ti_EnvSoundComponentT() {
    this.Name = null;
  }
  public static ti_EnvSoundComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return ti_EnvSoundComponent.GetRootAsti_EnvSoundComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    ti_EnvSoundComponent.Finishti_EnvSoundComponentBuffer(fbb, ti_EnvSoundComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
