// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ti_PokemonModelComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ti_PokemonModelComponent GetRootAsti_PokemonModelComponent(ByteBuffer _bb) { return GetRootAsti_PokemonModelComponent(_bb, new ti_PokemonModelComponent()); }
  public static ti_PokemonModelComponent GetRootAsti_PokemonModelComponent(ByteBuffer _bb, ti_PokemonModelComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ti_PokemonModelComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort NationalDexId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort FormId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public bool Res2 { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool Res3 { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public uint Res4 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public float Res5 { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public uint Res6 { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Res7 { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool Res8 { get { int o = __p.__offset(20); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Titan.TrinityScene.ti_PokemonModelComponent> Createti_PokemonModelComponent(FlatBufferBuilder builder,
      ushort national_dex_id = 0,
      ushort form_id = 0,
      bool res_2 = false,
      bool res_3 = false,
      uint res_4 = 0,
      float res_5 = 0.0f,
      uint res_6 = 0,
      uint res_7 = 0,
      bool res_8 = false) {
    builder.StartTable(9);
    ti_PokemonModelComponent.AddRes7(builder, res_7);
    ti_PokemonModelComponent.AddRes6(builder, res_6);
    ti_PokemonModelComponent.AddRes5(builder, res_5);
    ti_PokemonModelComponent.AddRes4(builder, res_4);
    ti_PokemonModelComponent.AddFormId(builder, form_id);
    ti_PokemonModelComponent.AddNationalDexId(builder, national_dex_id);
    ti_PokemonModelComponent.AddRes8(builder, res_8);
    ti_PokemonModelComponent.AddRes3(builder, res_3);
    ti_PokemonModelComponent.AddRes2(builder, res_2);
    return ti_PokemonModelComponent.Endti_PokemonModelComponent(builder);
  }

  public static void Startti_PokemonModelComponent(FlatBufferBuilder builder) { builder.StartTable(9); }
  public static void AddNationalDexId(FlatBufferBuilder builder, ushort nationalDexId) { builder.AddUshort(0, nationalDexId, 0); }
  public static void AddFormId(FlatBufferBuilder builder, ushort formId) { builder.AddUshort(1, formId, 0); }
  public static void AddRes2(FlatBufferBuilder builder, bool res2) { builder.AddBool(2, res2, false); }
  public static void AddRes3(FlatBufferBuilder builder, bool res3) { builder.AddBool(3, res3, false); }
  public static void AddRes4(FlatBufferBuilder builder, uint res4) { builder.AddUint(4, res4, 0); }
  public static void AddRes5(FlatBufferBuilder builder, float res5) { builder.AddFloat(5, res5, 0.0f); }
  public static void AddRes6(FlatBufferBuilder builder, uint res6) { builder.AddUint(6, res6, 0); }
  public static void AddRes7(FlatBufferBuilder builder, uint res7) { builder.AddUint(7, res7, 0); }
  public static void AddRes8(FlatBufferBuilder builder, bool res8) { builder.AddBool(8, res8, false); }
  public static Offset<Titan.TrinityScene.ti_PokemonModelComponent> Endti_PokemonModelComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.ti_PokemonModelComponent>(o);
  }
  public static void Finishti_PokemonModelComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.ti_PokemonModelComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedti_PokemonModelComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.ti_PokemonModelComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public ti_PokemonModelComponentT UnPack() {
    var _o = new ti_PokemonModelComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ti_PokemonModelComponentT _o) {
    _o.NationalDexId = this.NationalDexId;
    _o.FormId = this.FormId;
    _o.Res2 = this.Res2;
    _o.Res3 = this.Res3;
    _o.Res4 = this.Res4;
    _o.Res5 = this.Res5;
    _o.Res6 = this.Res6;
    _o.Res7 = this.Res7;
    _o.Res8 = this.Res8;
  }
  public static Offset<Titan.TrinityScene.ti_PokemonModelComponent> Pack(FlatBufferBuilder builder, ti_PokemonModelComponentT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.ti_PokemonModelComponent>);
    return Createti_PokemonModelComponent(
      builder,
      _o.NationalDexId,
      _o.FormId,
      _o.Res2,
      _o.Res3,
      _o.Res4,
      _o.Res5,
      _o.Res6,
      _o.Res7,
      _o.Res8);
  }
}

public class ti_PokemonModelComponentT
{
  public ushort NationalDexId { get; set; }
  public ushort FormId { get; set; }
  public bool Res2 { get; set; }
  public bool Res3 { get; set; }
  public uint Res4 { get; set; }
  public float Res5 { get; set; }
  public uint Res6 { get; set; }
  public uint Res7 { get; set; }
  public bool Res8 { get; set; }

  public ti_PokemonModelComponentT() {
    this.NationalDexId = 0;
    this.FormId = 0;
    this.Res2 = false;
    this.Res3 = false;
    this.Res4 = 0;
    this.Res5 = 0.0f;
    this.Res6 = 0;
    this.Res7 = 0;
    this.Res8 = false;
  }
  public static ti_PokemonModelComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return ti_PokemonModelComponent.GetRootAsti_PokemonModelComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    ti_PokemonModelComponent.Finishti_PokemonModelComponentBuffer(fbb, ti_PokemonModelComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
