// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct trinity_CameraEntity : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static trinity_CameraEntity GetRootAstrinity_CameraEntity(ByteBuffer _bb) { return GetRootAstrinity_CameraEntity(_bb, new trinity_CameraEntity()); }
  public static trinity_CameraEntity GetRootAstrinity_CameraEntity(ByteBuffer _bb, trinity_CameraEntity obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public trinity_CameraEntity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string CameraName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCameraNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetCameraNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetCameraNameArray() { return __p.__vector_as_array<byte>(4); }
  public uint Res1 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public Vec3f? Unk2 { get { int o = __p.__offset(8); return o != 0 ? (Vec3f?)(new Vec3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Vec3f? Unk3 { get { int o = __p.__offset(10); return o != 0 ? (Vec3f?)(new Vec3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Unk4 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Unk5 { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Unk6 { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Unk7 { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public uint Res8 { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte Unk9 { get { int o = __p.__offset(22); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public string Unk10 { get { int o = __p.__offset(24); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnk10Bytes() { return __p.__vector_as_span<byte>(24, 1); }
#else
  public ArraySegment<byte>? GetUnk10Bytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public byte[] GetUnk10Array() { return __p.__vector_as_array<byte>(24); }
  public uint Res11 { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Res12 { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte Res13 { get { int o = __p.__offset(30); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<Titan.TrinityScene.trinity_CameraEntity> Createtrinity_CameraEntity(FlatBufferBuilder builder,
      StringOffset camera_nameOffset = default(StringOffset),
      uint res_1 = 0,
      Vec3fT unk_2 = null,
      Vec3fT unk_3 = null,
      float unk_4 = 0.0f,
      float unk_5 = 0.0f,
      float unk_6 = 0.0f,
      float unk_7 = 0.0f,
      uint res_8 = 0,
      byte unk_9 = 0,
      StringOffset unk_10Offset = default(StringOffset),
      uint res_11 = 0,
      uint res_12 = 0,
      byte res_13 = 0) {
    builder.StartTable(14);
    trinity_CameraEntity.AddRes12(builder, res_12);
    trinity_CameraEntity.AddRes11(builder, res_11);
    trinity_CameraEntity.AddUnk10(builder, unk_10Offset);
    trinity_CameraEntity.AddRes8(builder, res_8);
    trinity_CameraEntity.AddUnk7(builder, unk_7);
    trinity_CameraEntity.AddUnk6(builder, unk_6);
    trinity_CameraEntity.AddUnk5(builder, unk_5);
    trinity_CameraEntity.AddUnk4(builder, unk_4);
    trinity_CameraEntity.AddUnk3(builder, Vec3f.Pack(builder, unk_3));
    trinity_CameraEntity.AddUnk2(builder, Vec3f.Pack(builder, unk_2));
    trinity_CameraEntity.AddRes1(builder, res_1);
    trinity_CameraEntity.AddCameraName(builder, camera_nameOffset);
    trinity_CameraEntity.AddRes13(builder, res_13);
    trinity_CameraEntity.AddUnk9(builder, unk_9);
    return trinity_CameraEntity.Endtrinity_CameraEntity(builder);
  }

  public static void Starttrinity_CameraEntity(FlatBufferBuilder builder) { builder.StartTable(14); }
  public static void AddCameraName(FlatBufferBuilder builder, StringOffset cameraNameOffset) { builder.AddOffset(0, cameraNameOffset.Value, 0); }
  public static void AddRes1(FlatBufferBuilder builder, uint res1) { builder.AddUint(1, res1, 0); }
  public static void AddUnk2(FlatBufferBuilder builder, Offset<Vec3f> unk2Offset) { builder.AddStruct(2, unk2Offset.Value, 0); }
  public static void AddUnk3(FlatBufferBuilder builder, Offset<Vec3f> unk3Offset) { builder.AddStruct(3, unk3Offset.Value, 0); }
  public static void AddUnk4(FlatBufferBuilder builder, float unk4) { builder.AddFloat(4, unk4, 0.0f); }
  public static void AddUnk5(FlatBufferBuilder builder, float unk5) { builder.AddFloat(5, unk5, 0.0f); }
  public static void AddUnk6(FlatBufferBuilder builder, float unk6) { builder.AddFloat(6, unk6, 0.0f); }
  public static void AddUnk7(FlatBufferBuilder builder, float unk7) { builder.AddFloat(7, unk7, 0.0f); }
  public static void AddRes8(FlatBufferBuilder builder, uint res8) { builder.AddUint(8, res8, 0); }
  public static void AddUnk9(FlatBufferBuilder builder, byte unk9) { builder.AddByte(9, unk9, 0); }
  public static void AddUnk10(FlatBufferBuilder builder, StringOffset unk10Offset) { builder.AddOffset(10, unk10Offset.Value, 0); }
  public static void AddRes11(FlatBufferBuilder builder, uint res11) { builder.AddUint(11, res11, 0); }
  public static void AddRes12(FlatBufferBuilder builder, uint res12) { builder.AddUint(12, res12, 0); }
  public static void AddRes13(FlatBufferBuilder builder, byte res13) { builder.AddByte(13, res13, 0); }
  public static Offset<Titan.TrinityScene.trinity_CameraEntity> Endtrinity_CameraEntity(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.trinity_CameraEntity>(o);
  }
  public static void Finishtrinity_CameraEntityBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.trinity_CameraEntity> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedtrinity_CameraEntityBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.trinity_CameraEntity> offset) { builder.FinishSizePrefixed(offset.Value); }
  public trinity_CameraEntityT UnPack() {
    var _o = new trinity_CameraEntityT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(trinity_CameraEntityT _o) {
    _o.CameraName = this.CameraName;
    _o.Res1 = this.Res1;
    _o.Unk2 = this.Unk2.HasValue ? this.Unk2.Value.UnPack() : null;
    _o.Unk3 = this.Unk3.HasValue ? this.Unk3.Value.UnPack() : null;
    _o.Unk4 = this.Unk4;
    _o.Unk5 = this.Unk5;
    _o.Unk6 = this.Unk6;
    _o.Unk7 = this.Unk7;
    _o.Res8 = this.Res8;
    _o.Unk9 = this.Unk9;
    _o.Unk10 = this.Unk10;
    _o.Res11 = this.Res11;
    _o.Res12 = this.Res12;
    _o.Res13 = this.Res13;
  }
  public static Offset<Titan.TrinityScene.trinity_CameraEntity> Pack(FlatBufferBuilder builder, trinity_CameraEntityT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.trinity_CameraEntity>);
    var _camera_name = _o.CameraName == null ? default(StringOffset) : builder.CreateString(_o.CameraName);
    var _unk_10 = _o.Unk10 == null ? default(StringOffset) : builder.CreateString(_o.Unk10);
    return Createtrinity_CameraEntity(
      builder,
      _camera_name,
      _o.Res1,
      _o.Unk2,
      _o.Unk3,
      _o.Unk4,
      _o.Unk5,
      _o.Unk6,
      _o.Unk7,
      _o.Res8,
      _o.Unk9,
      _unk_10,
      _o.Res11,
      _o.Res12,
      _o.Res13);
  }
}

public class trinity_CameraEntityT
{
  public string CameraName { get; set; }
  public uint Res1 { get; set; }
  public Vec3fT Unk2 { get; set; }
  public Vec3fT Unk3 { get; set; }
  public float Unk4 { get; set; }
  public float Unk5 { get; set; }
  public float Unk6 { get; set; }
  public float Unk7 { get; set; }
  public uint Res8 { get; set; }
  public byte Unk9 { get; set; }
  public string Unk10 { get; set; }
  public uint Res11 { get; set; }
  public uint Res12 { get; set; }
  public byte Res13 { get; set; }

  public trinity_CameraEntityT() {
    this.CameraName = null;
    this.Res1 = 0;
    this.Unk2 = new Vec3fT();
    this.Unk3 = new Vec3fT();
    this.Unk4 = 0.0f;
    this.Unk5 = 0.0f;
    this.Unk6 = 0.0f;
    this.Unk7 = 0.0f;
    this.Res8 = 0;
    this.Unk9 = 0;
    this.Unk10 = null;
    this.Res11 = 0;
    this.Res12 = 0;
    this.Res13 = 0;
  }
  public static trinity_CameraEntityT DeserializeFromBinary(byte[] fbBuffer) {
    return trinity_CameraEntity.GetRootAstrinity_CameraEntity(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    trinity_CameraEntity.Finishtrinity_CameraEntityBuffer(fbb, trinity_CameraEntity.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
