// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct trinity_ObjectSwitcher : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static trinity_ObjectSwitcher GetRootAstrinity_ObjectSwitcher(ByteBuffer _bb) { return GetRootAstrinity_ObjectSwitcher(_bb, new trinity_ObjectSwitcher()); }
  public static trinity_ObjectSwitcher GetRootAstrinity_ObjectSwitcher(ByteBuffer _bb, trinity_ObjectSwitcher obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public trinity_ObjectSwitcher __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Unk0 { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnk0Bytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUnk0Bytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUnk0Array() { return __p.__vector_as_array<byte>(4); }
  public string Unk1 { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnk1Bytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUnk1Bytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUnk1Array() { return __p.__vector_as_array<byte>(6); }

  public static Offset<Titan.TrinityScene.trinity_ObjectSwitcher> Createtrinity_ObjectSwitcher(FlatBufferBuilder builder,
      StringOffset unk_0Offset = default(StringOffset),
      StringOffset unk_1Offset = default(StringOffset)) {
    builder.StartTable(2);
    trinity_ObjectSwitcher.AddUnk1(builder, unk_1Offset);
    trinity_ObjectSwitcher.AddUnk0(builder, unk_0Offset);
    return trinity_ObjectSwitcher.Endtrinity_ObjectSwitcher(builder);
  }

  public static void Starttrinity_ObjectSwitcher(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUnk0(FlatBufferBuilder builder, StringOffset unk0Offset) { builder.AddOffset(0, unk0Offset.Value, 0); }
  public static void AddUnk1(FlatBufferBuilder builder, StringOffset unk1Offset) { builder.AddOffset(1, unk1Offset.Value, 0); }
  public static Offset<Titan.TrinityScene.trinity_ObjectSwitcher> Endtrinity_ObjectSwitcher(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.trinity_ObjectSwitcher>(o);
  }
  public static void Finishtrinity_ObjectSwitcherBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.trinity_ObjectSwitcher> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedtrinity_ObjectSwitcherBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.trinity_ObjectSwitcher> offset) { builder.FinishSizePrefixed(offset.Value); }
  public trinity_ObjectSwitcherT UnPack() {
    var _o = new trinity_ObjectSwitcherT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(trinity_ObjectSwitcherT _o) {
    _o.Unk0 = this.Unk0;
    _o.Unk1 = this.Unk1;
  }
  public static Offset<Titan.TrinityScene.trinity_ObjectSwitcher> Pack(FlatBufferBuilder builder, trinity_ObjectSwitcherT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.trinity_ObjectSwitcher>);
    var _unk_0 = _o.Unk0 == null ? default(StringOffset) : builder.CreateString(_o.Unk0);
    var _unk_1 = _o.Unk1 == null ? default(StringOffset) : builder.CreateString(_o.Unk1);
    return Createtrinity_ObjectSwitcher(
      builder,
      _unk_0,
      _unk_1);
  }
}

public class trinity_ObjectSwitcherT
{
  public string Unk0 { get; set; }
  public string Unk1 { get; set; }

  public trinity_ObjectSwitcherT() {
    this.Unk0 = null;
    this.Unk1 = null;
  }
  public static trinity_ObjectSwitcherT DeserializeFromBinary(byte[] fbBuffer) {
    return trinity_ObjectSwitcher.GetRootAstrinity_ObjectSwitcher(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    trinity_ObjectSwitcher.Finishtrinity_ObjectSwitcherBuffer(fbb, trinity_ObjectSwitcher.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
