// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct trinity_LightApplierComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static trinity_LightApplierComponent GetRootAstrinity_LightApplierComponent(ByteBuffer _bb) { return GetRootAstrinity_LightApplierComponent(_bb, new trinity_LightApplierComponent()); }
  public static trinity_LightApplierComponent GetRootAstrinity_LightApplierComponent(ByteBuffer _bb, trinity_LightApplierComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public trinity_LightApplierComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string FilePath { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilePathBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFilePathBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFilePathArray() { return __p.__vector_as_array<byte>(4); }
  public uint Unk1 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public float Unk2 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public bool Unk3 { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string Unk4 { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnk4Bytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetUnk4Bytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetUnk4Array() { return __p.__vector_as_array<byte>(12); }
  public uint Unk5 { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool Unk6 { get { int o = __p.__offset(16); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public uint Unk7 { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool Unk8 { get { int o = __p.__offset(20); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool Unk9 { get { int o = __p.__offset(22); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Titan.TrinityScene.trinity_LightApplierComponent> Createtrinity_LightApplierComponent(FlatBufferBuilder builder,
      StringOffset file_pathOffset = default(StringOffset),
      uint unk_1 = 0,
      float unk_2 = 0.0f,
      bool unk_3 = false,
      StringOffset unk_4Offset = default(StringOffset),
      uint unk_5 = 0,
      bool unk_6 = false,
      uint unk_7 = 0,
      bool unk_8 = false,
      bool unk_9 = false) {
    builder.StartTable(10);
    trinity_LightApplierComponent.AddUnk7(builder, unk_7);
    trinity_LightApplierComponent.AddUnk5(builder, unk_5);
    trinity_LightApplierComponent.AddUnk4(builder, unk_4Offset);
    trinity_LightApplierComponent.AddUnk2(builder, unk_2);
    trinity_LightApplierComponent.AddUnk1(builder, unk_1);
    trinity_LightApplierComponent.AddFilePath(builder, file_pathOffset);
    trinity_LightApplierComponent.AddUnk9(builder, unk_9);
    trinity_LightApplierComponent.AddUnk8(builder, unk_8);
    trinity_LightApplierComponent.AddUnk6(builder, unk_6);
    trinity_LightApplierComponent.AddUnk3(builder, unk_3);
    return trinity_LightApplierComponent.Endtrinity_LightApplierComponent(builder);
  }

  public static void Starttrinity_LightApplierComponent(FlatBufferBuilder builder) { builder.StartTable(10); }
  public static void AddFilePath(FlatBufferBuilder builder, StringOffset filePathOffset) { builder.AddOffset(0, filePathOffset.Value, 0); }
  public static void AddUnk1(FlatBufferBuilder builder, uint unk1) { builder.AddUint(1, unk1, 0); }
  public static void AddUnk2(FlatBufferBuilder builder, float unk2) { builder.AddFloat(2, unk2, 0.0f); }
  public static void AddUnk3(FlatBufferBuilder builder, bool unk3) { builder.AddBool(3, unk3, false); }
  public static void AddUnk4(FlatBufferBuilder builder, StringOffset unk4Offset) { builder.AddOffset(4, unk4Offset.Value, 0); }
  public static void AddUnk5(FlatBufferBuilder builder, uint unk5) { builder.AddUint(5, unk5, 0); }
  public static void AddUnk6(FlatBufferBuilder builder, bool unk6) { builder.AddBool(6, unk6, false); }
  public static void AddUnk7(FlatBufferBuilder builder, uint unk7) { builder.AddUint(7, unk7, 0); }
  public static void AddUnk8(FlatBufferBuilder builder, bool unk8) { builder.AddBool(8, unk8, false); }
  public static void AddUnk9(FlatBufferBuilder builder, bool unk9) { builder.AddBool(9, unk9, false); }
  public static Offset<Titan.TrinityScene.trinity_LightApplierComponent> Endtrinity_LightApplierComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.trinity_LightApplierComponent>(o);
  }
  public static void Finishtrinity_LightApplierComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.trinity_LightApplierComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedtrinity_LightApplierComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.trinity_LightApplierComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public trinity_LightApplierComponentT UnPack() {
    var _o = new trinity_LightApplierComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(trinity_LightApplierComponentT _o) {
    _o.FilePath = this.FilePath;
    _o.Unk1 = this.Unk1;
    _o.Unk2 = this.Unk2;
    _o.Unk3 = this.Unk3;
    _o.Unk4 = this.Unk4;
    _o.Unk5 = this.Unk5;
    _o.Unk6 = this.Unk6;
    _o.Unk7 = this.Unk7;
    _o.Unk8 = this.Unk8;
    _o.Unk9 = this.Unk9;
  }
  public static Offset<Titan.TrinityScene.trinity_LightApplierComponent> Pack(FlatBufferBuilder builder, trinity_LightApplierComponentT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.trinity_LightApplierComponent>);
    var _file_path = _o.FilePath == null ? default(StringOffset) : builder.CreateString(_o.FilePath);
    var _unk_4 = _o.Unk4 == null ? default(StringOffset) : builder.CreateString(_o.Unk4);
    return Createtrinity_LightApplierComponent(
      builder,
      _file_path,
      _o.Unk1,
      _o.Unk2,
      _o.Unk3,
      _unk_4,
      _o.Unk5,
      _o.Unk6,
      _o.Unk7,
      _o.Unk8,
      _o.Unk9);
  }
}

public class trinity_LightApplierComponentT
{
  public string FilePath { get; set; }
  public uint Unk1 { get; set; }
  public float Unk2 { get; set; }
  public bool Unk3 { get; set; }
  public string Unk4 { get; set; }
  public uint Unk5 { get; set; }
  public bool Unk6 { get; set; }
  public uint Unk7 { get; set; }
  public bool Unk8 { get; set; }
  public bool Unk9 { get; set; }

  public trinity_LightApplierComponentT() {
    this.FilePath = null;
    this.Unk1 = 0;
    this.Unk2 = 0.0f;
    this.Unk3 = false;
    this.Unk4 = null;
    this.Unk5 = 0;
    this.Unk6 = false;
    this.Unk7 = 0;
    this.Unk8 = false;
    this.Unk9 = false;
  }
  public static trinity_LightApplierComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return trinity_LightApplierComponent.GetRootAstrinity_LightApplierComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    trinity_LightApplierComponent.Finishtrinity_LightApplierComponentBuffer(fbb, trinity_LightApplierComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
