// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Titan.TrinityScene
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct trinity_VATComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static trinity_VATComponent GetRootAstrinity_VATComponent(ByteBuffer _bb) { return GetRootAstrinity_VATComponent(_bb, new trinity_VATComponent()); }
  public static trinity_VATComponent GetRootAstrinity_VATComponent(ByteBuffer _bb, trinity_VATComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public trinity_VATComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string FilePath { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFilePathBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFilePathBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFilePathArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Titan.TrinityScene.trinity_VATComponent> Createtrinity_VATComponent(FlatBufferBuilder builder,
      StringOffset file_pathOffset = default(StringOffset)) {
    builder.StartTable(1);
    trinity_VATComponent.AddFilePath(builder, file_pathOffset);
    return trinity_VATComponent.Endtrinity_VATComponent(builder);
  }

  public static void Starttrinity_VATComponent(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddFilePath(FlatBufferBuilder builder, StringOffset filePathOffset) { builder.AddOffset(0, filePathOffset.Value, 0); }
  public static Offset<Titan.TrinityScene.trinity_VATComponent> Endtrinity_VATComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Titan.TrinityScene.trinity_VATComponent>(o);
  }
  public static void Finishtrinity_VATComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.trinity_VATComponent> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedtrinity_VATComponentBuffer(FlatBufferBuilder builder, Offset<Titan.TrinityScene.trinity_VATComponent> offset) { builder.FinishSizePrefixed(offset.Value); }
  public trinity_VATComponentT UnPack() {
    var _o = new trinity_VATComponentT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(trinity_VATComponentT _o) {
    _o.FilePath = this.FilePath;
  }
  public static Offset<Titan.TrinityScene.trinity_VATComponent> Pack(FlatBufferBuilder builder, trinity_VATComponentT _o) {
    if (_o == null) return default(Offset<Titan.TrinityScene.trinity_VATComponent>);
    var _file_path = _o.FilePath == null ? default(StringOffset) : builder.CreateString(_o.FilePath);
    return Createtrinity_VATComponent(
      builder,
      _file_path);
  }
}

public class trinity_VATComponentT
{
  public string FilePath { get; set; }

  public trinity_VATComponentT() {
    this.FilePath = null;
  }
  public static trinity_VATComponentT DeserializeFromBinary(byte[] fbBuffer) {
    return trinity_VATComponent.GetRootAstrinity_VATComponent(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    trinity_VATComponent.Finishtrinity_VATComponentBuffer(fbb, trinity_VATComponent.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


}
