// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.audio.fb
{

public enum GeneratorType : uint
{
  AreaSound = 0,
  ShapeSound = 1,
  AmbientSound = 2,
  MultiDirectionSound = 3,
  MultiSourceSound = 4,
};


}
