// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.math.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AABB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static AABB GetRootAsAABB(ByteBuffer _bb) { return GetRootAsAABB(_bb, new AABB()); }
  public static AABB GetRootAsAABB(ByteBuffer _bb, AABB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AABB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gfl.math.fb.Vector3f? Min { get { int o = __p.__offset(4); return o != 0 ? (gfl.math.fb.Vector3f?)(new gfl.math.fb.Vector3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public gfl.math.fb.Vector3f? Max { get { int o = __p.__offset(6); return o != 0 ? (gfl.math.fb.Vector3f?)(new gfl.math.fb.Vector3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartAABB(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMin(FlatBufferBuilder builder, Offset<gfl.math.fb.Vector3f> minOffset) { builder.AddStruct(0, minOffset.Value, 0); }
  public static void AddMax(FlatBufferBuilder builder, Offset<gfl.math.fb.Vector3f> maxOffset) { builder.AddStruct(1, maxOffset.Value, 0); }
  public static Offset<gfl.math.fb.AABB> EndAABB(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.math.fb.AABB>(o);
  }
  public AABBT UnPack() {
    var _o = new AABBT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(AABBT _o) {
    _o.Min = this.Min.HasValue ? this.Min.Value.UnPack() : null;
    _o.Max = this.Max.HasValue ? this.Max.Value.UnPack() : null;
  }
  public static Offset<gfl.math.fb.AABB> Pack(FlatBufferBuilder builder, AABBT _o) {
    if (_o == null) return default(Offset<gfl.math.fb.AABB>);
    StartAABB(builder);
    AddMin(builder, gfl.math.fb.Vector3f.Pack(builder, _o.Min));
    AddMax(builder, gfl.math.fb.Vector3f.Pack(builder, _o.Max));
    return EndAABB(builder);
  }
}

public class AABBT
{
  public gfl.math.fb.Vector3fT Min { get; set; }
  public gfl.math.fb.Vector3fT Max { get; set; }

  public AABBT() {
    this.Min = new gfl.math.fb.Vector3fT();
    this.Max = new gfl.math.fb.Vector3fT();
  }
}


}
