// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.math.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SRT : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static SRT GetRootAsSRT(ByteBuffer _bb) { return GetRootAsSRT(_bb, new SRT()); }
  public static SRT GetRootAsSRT(ByteBuffer _bb, SRT obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SRT __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gfl.math.fb.Vector3f? Scale { get { int o = __p.__offset(4); return o != 0 ? (gfl.math.fb.Vector3f?)(new gfl.math.fb.Vector3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public gfl.math.fb.Vector3f? Rotate { get { int o = __p.__offset(6); return o != 0 ? (gfl.math.fb.Vector3f?)(new gfl.math.fb.Vector3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public gfl.math.fb.Vector3f? Translate { get { int o = __p.__offset(8); return o != 0 ? (gfl.math.fb.Vector3f?)(new gfl.math.fb.Vector3f()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartSRT(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddScale(FlatBufferBuilder builder, Offset<gfl.math.fb.Vector3f> scaleOffset) { builder.AddStruct(0, scaleOffset.Value, 0); }
  public static void AddRotate(FlatBufferBuilder builder, Offset<gfl.math.fb.Vector3f> rotateOffset) { builder.AddStruct(1, rotateOffset.Value, 0); }
  public static void AddTranslate(FlatBufferBuilder builder, Offset<gfl.math.fb.Vector3f> translateOffset) { builder.AddStruct(2, translateOffset.Value, 0); }
  public static Offset<gfl.math.fb.SRT> EndSRT(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<gfl.math.fb.SRT>(o);
  }
  public SRTT UnPack() {
    var _o = new SRTT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SRTT _o) {
    _o.Scale = this.Scale.HasValue ? this.Scale.Value.UnPack() : null;
    _o.Rotate = this.Rotate.HasValue ? this.Rotate.Value.UnPack() : null;
    _o.Translate = this.Translate.HasValue ? this.Translate.Value.UnPack() : null;
  }
  public static Offset<gfl.math.fb.SRT> Pack(FlatBufferBuilder builder, SRTT _o) {
    if (_o == null) return default(Offset<gfl.math.fb.SRT>);
    StartSRT(builder);
    AddScale(builder, gfl.math.fb.Vector3f.Pack(builder, _o.Scale));
    AddRotate(builder, gfl.math.fb.Vector3f.Pack(builder, _o.Rotate));
    AddTranslate(builder, gfl.math.fb.Vector3f.Pack(builder, _o.Translate));
    return EndSRT(builder);
  }
}

public partial class SRTT
{
  public gfl.math.fb.Vector3fT Scale { get; set; }
  public gfl.math.fb.Vector3fT Rotate { get; set; }
  public gfl.math.fb.Vector3fT Translate { get; set; }

  public SRTT() {
    this.Scale = new gfl.math.fb.Vector3fT();
    this.Rotate = new gfl.math.fb.Vector3fT();
    this.Translate = new gfl.math.fb.Vector3fT();
  }
}


}
