// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.math.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Vector2i : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vector2i __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int X { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Y { get { return __p.bb.GetInt(__p.bb_pos + 4); } }

  public static Offset<gfl.math.fb.Vector2i> CreateVector2i(FlatBufferBuilder builder, int X, int Y) {
    builder.Prep(4, 8);
    builder.PutInt(Y);
    builder.PutInt(X);
    return new Offset<gfl.math.fb.Vector2i>(builder.Offset);
  }
  public Vector2iT UnPack() {
    var _o = new Vector2iT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(Vector2iT _o) {
    _o.X = this.X;
    _o.Y = this.Y;
  }
  public static Offset<gfl.math.fb.Vector2i> Pack(FlatBufferBuilder builder, Vector2iT _o) {
    if (_o == null) return default(Offset<gfl.math.fb.Vector2i>);
    return CreateVector2i(
      builder,
      _o.X,
      _o.Y);
  }
}

public class Vector2iT
{
  public int X { get; set; }
  public int Y { get; set; }

  public Vector2iT() {
    this.X = 0;
    this.Y = 0;
  }
}


}
