// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.math.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Vector3i : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vector3i __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int X { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Y { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public int Z { get { return __p.bb.GetInt(__p.bb_pos + 8); } }

  public static Offset<gfl.math.fb.Vector3i> CreateVector3i(FlatBufferBuilder builder, int X, int Y, int Z) {
    builder.Prep(4, 12);
    builder.PutInt(Z);
    builder.PutInt(Y);
    builder.PutInt(X);
    return new Offset<gfl.math.fb.Vector3i>(builder.Offset);
  }
  public Vector3iT UnPack() {
    var _o = new Vector3iT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(Vector3iT _o) {
    _o.X = this.X;
    _o.Y = this.Y;
    _o.Z = this.Z;
  }
  public static Offset<gfl.math.fb.Vector3i> Pack(FlatBufferBuilder builder, Vector3iT _o) {
    if (_o == null) return default(Offset<gfl.math.fb.Vector3i>);
    return CreateVector3i(
      builder,
      _o.X,
      _o.Y,
      _o.Z);
  }
}

public class Vector3iT
{
  public int X { get; set; }
  public int Y { get; set; }
  public int Z { get; set; }

  public Vector3iT() {
    this.X = 0;
    this.Y = 0;
    this.Z = 0;
  }
}


}
