// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace gfl.math.fb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Vector2f : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vector2f __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }

  public static Offset<gfl.math.fb.Vector2f> CreateVector2f(FlatBufferBuilder builder, float X, float Y) {
    builder.Prep(4, 8);
    builder.PutFloat(Y);
    builder.PutFloat(X);
    return new Offset<gfl.math.fb.Vector2f>(builder.Offset);
  }
  public Vector2fT UnPack() {
    var _o = new Vector2fT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(Vector2fT _o) {
    _o.X = this.X;
    _o.Y = this.Y;
  }
  public static Offset<gfl.math.fb.Vector2f> Pack(FlatBufferBuilder builder, Vector2fT _o) {
    if (_o == null) return default(Offset<gfl.math.fb.Vector2f>);
    return CreateVector2f(
      builder,
      _o.X,
      _o.Y);
  }
}

public class Vector2fT
{
  public float X { get; set; }
  public float Y { get; set; }

  public Vector2fT() {
    this.X = 0.0f;
    this.Y = 0.0f;
  }
}


}
